### ISSUE TITLE
multi-page app stopped working with new DEPS API

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#104]
With the latest changes `Stipple.init()` checks whether a dependency entry of the key `MODELDEPID` already exists and if not, adds it to the DEPS dict.
This breaks multi-page apps because the deps include the wrong js file.

My current workaround is to clear the entry before calling `init()`
```julia
    delete!(Stipple.DEPS, Stipple.MODELDEPID)
    model = init(Example) |> handlers |> ui |> html
```

@essenciary, @AbhimanyuAryan

Wouldn't it be better to create entries for each ReactiveModel type?
We would need to modify `deps()` to require a ReactiveType (There is already such a method, but it's not used, I think.)

Furthermore `deps()` is called from `layout()` which takes a channel only and no ModelType, and `layout()` is called from `page()`, which then would also need to always pass on the model type.

**Comment by hhaensel** [comment]
Not sure, whether we would need `MODELDEPID` any longer. But we would also need to modify `injectdeps()` to include the model type.

**Comment by hhaensel** [comment]
I think this issue is also relevant for testing and development. Imagine you develop a model and you want to test a variant that you name differently, or you jump to another project and want to test the page without reloading Stipple. Due to line 806 in `Stipple.jl` the page will always include the name of the model that was first initialised with `Stipple.init()`.

My conclusion is, MODELDEPID must be replaced by a model type specific entry.
In my draft PR #105 I chose the ReactiveModel type itself, but we could also use a string, e.g. `vm(ModelType)`.
The latter one would overwrite definitions, if a model has been redefined via `@reactive!`. In the current draft the entry would persist and a new one (which has the same name) is created.

**Comment by essenciary** [comment]
I need to look closely - but could it be related to the fact that you're using global models? If you initiate the model in the `route`, wouldn't that create a new response with the new model?

**Comment by hhaensel** [comment]
Here's an MWE:
```julia
@reactive! mutable struct Example1 <: ReactiveModel end
@reactive! mutable struct Example2 <: ReactiveModel end

ex1 = init(Example1)
ex2 = init(Example2)
```

```julia
julia> Stipple.deps(ex2)
9-element Vector{String}:
 "<script>window.CHANNEL = 'MCDYKEMVMSFNBEMMXTRGVJEEVLCYNIQE';</script>"
 "<script src=\"/genie.jl/master/assets/js/channels.js\"></script>"
 "<script src=\"/stipple.jl/master/assets/js/underscore-min.js\"></script>"
 "<script src=\"/stipple.jl/master/assets/js/vue.js\"></script>"
 "<script src=\"/stipple.jl/master/assets/js/stipplecore.js\"></script>"
 "<script src=\"/stipple.jl/master/assets/js/vue_filters.js\" defer></script>"
 "<script src=\"/stipple.jl/master/assets/js/watchers.js\"></script>"
 "<script src=\"/stipple.jl/master/assets/js/keepalive.js\" defer></script>"
 "<script src=\"/stipple.jl/master/assets/js/example1.js\" defer></script>"
```
The last line should read
```julia
 "<script src=\"/stipple.jl/master/assets/js/example2.js\" defer></script>"
```

**Comment by hhaensel** [comment]
You can inspect Stipple.DEPS, to see what's happening

**Comment by essenciary** [comment]
Merged proposed PR
