### ISSUE TITLE
@reactive! not working on Julia 1.8

### ISSUE THREAD

**Issue by essenciary** [GenieFramework/Stipple.jl#106]
```julia
julia> @reactive! mutable struct Example1 <: ReactiveModel end
ERROR: setfield!: const field .name of type TypeName cannot be changed
Stacktrace:
 [1] setproperty!(x::Core.TypeName, f::Symbol, v::Symbol)
   @ Base ./Base.jl:39
 [2] top-level scope
   @ ~/.julia/packages/Stipple/ikRxD/src/Stipple.jl:1291
```

If it can not be fixed, I suggest removing the feature. @hhaensel

**Comment by hhaensel** [comment]
We could skip setting the name for Julia 1.8
It would still work but wouldn't look so nice. It's so useful for development.
Moreover there is an open issue in BSON with the same error. Let's see what's happening there

**Comment by essenciary** [comment]
What does it mean that it doesn't look that nice? 
If you recommend keeping it, as is, sure. Do you want to make a PR for the change?

**Comment by hhaensel** [comment]
Well, I fixed this already 4 days ago 😉

**Comment by hhaensel** [comment]
Not nice means, the name of the type is not the original one, but we assign a variable with the correct name with that strangely named struct. When you call it, you see that the name is different.

**Comment by hhaensel** [comment]
There's another problem with redefining a model. Due to line 819ff in `Stipple.jl`

```julia
      if ! Genie.Router.isroute(Symbol(m))
        Genie.Router.route(Genie.Assets.asset_path(assets_config, :js, file = endpoint), named = Symbol(m)) do
          Stipple.Elements.vue_integration(m; vue_app_name, debounce, core_theme, transport) |> Genie.Renderer.Js.js
        end
      end
```
the model's js file, e.g. `model.js` is not replaced after redifining a model.
I you are in the design phase and want to change your  model, you also need to

```julia
Genie.Router.delete!(Symbol(Model))
```

**Comment by essenciary** [comment]
I'm on 1.8 and it's not a severe issue. The result is indeed multiple routes being added as models are renamed which is not great, but not breaking.

**Comment by essenciary** [comment]
Closing as fixed
