### ISSUE TITLE
@bind and @recur intransparent for path expressions with nested dicts

### ISSUE THREAD

**Issue by michaelfliegner** [GenieFramework/Stipple.jl#109]
I have working QUASAR code displaying from nested dicts, which seemingly cannot be refactored into stipple code. 

""" <input v-model="csect['contract_revision']['description']" v-on:keyup.enter="modContractRevision=true"/> """

the model is defined as follows"

@reactive mutable struct Model <: ReactiveModel

    modContractRevision::R{Bool} = false

    modProductitemRevision::R{Bool} = false

    addProductItem::R{Bool} = false

    csect::R{Dict{String,Any}} = Dict{String,Any}("contract_revision" => 1)

end

Refactoring using @bind does not produce working code: input is ignored. Same problem with @recur.

I suppose @bind and @recur suppress evaluation of the "csect" subexpression.

Here is my MWE using v-model and v-for.

https://github.com/michaelfliegner/BitemporalReactive.jl/blob/master/ContractSectionSO.jl

**Comment by hhaensel** [comment]
I can't acces the link ...

**Comment by hhaensel** [comment]
In a very similar context I used
```julia
textfield(class="geld", "", nothing, "", v__if="name.length > 3", @bind("geld[3]", "number"), label=@data("name[3]"), :outlined, :filled, style="top: 75%; left:30%;")
```

**Comment by michaelfliegner** [comment]
Just made the repo public.
Sorry.


hhaensel ***@***.***> schrieb am So., 8. Mai 2022, 00:43:

**Comment by hhaensel** [comment]
Currently only on my mobile, but I think line 117 should contain square brackets with a colon (non-notifying model field modification).
```julia
model.csect[!] = csectDict
```

**Comment by hhaensel** [comment]
I tried both, `textfield` and `@bind` with the current Stipple version, and I succeeded with both of them.
I placed my versions on top of your direct `input` binding to verify that fields synchronise.
```julia
textfield("Description", dense = true, label__color = "orange", bg__color = "white", R"""csect['product_items'][index]['productitem_revision']['description']""", @on("keyup.enter", "modProductitemRevision=true")),
itemlabel("Description"),
input(@bind("""csect["product_items"][index]["productitem_revision"]["description"]"""), @on("keyup.enter", "modProductitemRevision=true")),
itemlabel("Description"),
"""
<input v-model='csect["product_items"][index]["productitem_revision"]["description"]' v-on:keyup.enter="modProductitemRevision=true"/>      
""",

```

**Comment by michaelfliegner** [comment]
**A BIG BIG Thank You!**
