### ISSUE TITLE
[Help] Downloading a file from localhost

### ISSUE THREAD

**Issue by MariaHei** [GenieFramework/Stipple.jl#112]
Hi :)

I have been developing a small app with Stipple, and I'm having loads of fun with it! Thank you so much for developing this.

At the moment, my app is living on the localhost. I would like to add a feature where the user can download a file (from my local file system, on localhost). However, I can't seem to find a way to do this. It is suggested [here](https://gitter.im/essenciary/Genie.jl?at=5e9e20d063e7b73a5ff21d72) that a simple 
```
"<a href='path/to/my_file.csv' download='my_file.csv'>Download link</a>"
```
should suffice. However, no matter which file location or type I use, I always get a `Failed - No file` error.
If I try just finding the location of the file on the localhost, I also don't find it.

Do you know a solution to this problem?

**Comment by essenciary** [comment]
@MariaHei All the files placed inside the `public/` folder in the root of the app are publicly accessible. If the `public/` folder does not exist, create it. Then put the file inside the folder and use the `<a href...` approach you mentioned above. 

Ex: 
* file: `public/csv/my_file.csv`
* href: `<a href="/csv/my_file.csv" download>` <- do not put `public/` in the URL
