### ISSUE TITLE
multiuser

### ISSUE THREAD

**Issue by cwiese** [GenieFramework/Stipple.jl#116]
Can you point me to an example of MULTIUSER models?  I would also like to accept a Query param like so 

http://127.0.0.1:8000?state=Michigan 

This would filter the model for this "user" for michigan only.

How can I do that?

CHuck

**Comment by AbhimanyuAryan** [comment]
we had an example for that but currently it's broken: https://github.com/GenieFramework/StippleDemos/blob/master/_broken_/MultiUserApp.jl

I'll fix it and ping you here.

**Comment by essenciary** [comment]
All apps are multi-user _by default_ now (no shared state unless explicitly set)
https://github.com/GenieFramework/Stipple.jl/blob/358f182ec1f3d901362fb32a258471a31c02cff0/src/Stipple.jl#L269

**Comment by AbhimanyuAryan** [comment]
aah ok missed this. Thanks

**Comment by cwiese** [comment]
awsome !!!  - when a user go to the server with a Query Param like
http://127.0.0.1:8000/state=Michigan
how can I get "state"  .. this is not Model is ready?

**Comment by essenciary** [comment]
I'm not sure what you're trying to do. 

A GET/query param is sent on the initial server request over HTTP. It's part of the request and can be accessed in various ways, including 

```julia
using Genie.Requests
getpayload(:state)
```

or 

```julia
params(:state)
```

If you want to share state between multiple users based on the `state` GET/query param you need to set the model's channel to this shared "name". You can do it explicitly when you initialize the model: 

```julia
using Genie.Requests
Stipple.init(Model; channel = getpayload(:state)
```

**Comment by cwiese** [comment]
excellent thank you

**Comment by cwiese** [comment]
I am confused on where to put this "getpayload(:station)"

If I put in the  on(model.isready) it is not there... if i put elsewhere it runs on server start. - before ad user hits the URL

```
┌ Info: 
└ Web Server starting at http://127.0.0.1:8000 
Genie.AppServer.ServersCollection(Task (runnable) @0x000000014dd8e230, nothing)

julia> [ Info: GET /?station=ORD 200
[ Info: GET /stipple.jl/master/assets/css/stipplecore.css 200
[ Info: GET /stippleui.jl/master/assets/css/quasar.min.css 200
[ Info: GET /genie.jl/master/assets/js/channels.js 200
[ Info: GET /stipple.jl/master/assets/js/underscore-min.js 200
[ Info: GET /stipple.jl/master/assets/js/vue.js 200
[ Info: GET /stipple.jl/master/assets/js/stipplecore.js 200
[ Info: GET /stipple.jl/master/assets/js/watchers.js 200
[ Info: GET /stippleplotly.jl/master/assets/js/plotly2.min.js 200
[ Info: GET /stippleplotly.jl/master/assets/js/resizesensor.min.js 200
[ Info: GET /stippleplotly.jl/master/assets/js/lodash.min.js 200
[ Info: GET /stippleplotly.jl/master/assets/js/vueresize.min.js 200
[ Info: GET /stippleplotly.jl/master/assets/js/vueplotly.min.js 200
[ Info: GET /stippleui.jl/master/assets/js/quasar.umd.min.js 200
[ Info: GET /stipple.jl/master/assets/js/vue_filters.js 200
[ Info: GET /stipple.jl/master/assets/js/keepalive.js 200
[ Info: GET /stipple.jl/master/assets/js/fampages.js 200
```

**Comment by essenciary** [comment]
I don't understand what you're doing - can you show your code?

**Comment by cwiese** [comment]
I  added to route and it looks good so far !

**Comment by cwiese** [comment]
thank you
