### ISSUE TITLE
nested model properties 

### ISSUE THREAD

**Issue by cwiese** [GenieFramework/Stipple.jl#117]
my model has a daterange 

```
@reactive mutable struct Pages <: ReactiveModel
    daterange::R{DateRange} = DateRange(today(), (today() + Day(3)))
emnd
```

how do I refer to a nested properties ( :daterange.start will not work of course) 

```
cell([div(
        class = "q-pa-md",
        style = "max-width: 300px",
        [textfield(
            "",
            :daterange.start,
...'
````

**Comment by hhaensel** [comment]
`R"date.start"` or `Symbol("date.start")` should go the job.

**Comment by cwiese** [comment]
does not seem to work - here is a simple example

```
using Stipple, StippleUI

@reactive mutable struct Model <: ReactiveModel
  daterange::R{DateRange} = DateRange()
end

function ui(model)
    page(
        model,
        textfield("t2", Symbol("daterange.start"), "", placeholder = "no output yet ...", label = "DataRange", :outlined, :filled, type = "textfield")
        #textfield("t2", :daterange, "", placeholder = "no output yet ...", label = "DataRange", :outlined, :filled, type = "textfield")
      )
end
  

route("/") do
    hs_model = Model |> init |> ui
end 

up()

```

**Comment by hhaensel** [comment]
I'll have a look when I'm back at my computer. Currently only on my mobile. I think, the point is string to date conversion. I know there are date pi kers ...
Maybe you could try that
>

**Comment by cwiese** [comment]
Oddly in the datepicker example - they use a Text Field to show a date - in the popup button.  I want to show a range. 
```
inputdate::R{Date} = today()
```

**Comment by cwiese** [comment]
I am using DateRange (single) .. and I

**Comment by cwiese** [comment]
maybe I will switch to 2 dates

**Comment by wildart** [comment]
The date isn't showing because `render` function for `DateRange` renames fields to `from` & `to`:
https://github.com/GenieFramework/StippleUI.jl/blob/231c7aca8cd8e03288f483477271b815c10186ec/src/DatePickers.jl#L135-L137

When you define field name as `Symbol("daterange.from")` in `textfield` call, the date is showed correctly.

**Comment by cwiese** [comment]
Thank you Art - I need to dig more.

**Comment by AbhimanyuAryan** [comment]
Thanks, Art. @cwiese did it work for you?

**Comment by wildart** [comment]
Why are the names different? It's confusing.

**Comment by AbhimanyuAryan** [comment]
@wildart will discuss this with @essenciary @hhaensel and if there's no specific reason for different names. We can use `start` `end`

**Comment by essenciary** [comment]
While it's good to keep the same names in principle, I'm not sure here: 
1/ Quasar does not always make the best naming decisions, and this is one example
2/ Stipple abstracts away and improves the Quasar API (where possible) making the API "julian" - many names don't translate well to Julia
3/ Why do we even need to know how props are called in Quasar? This should be a standalone element with its own docs.
