### ISSUE TITLE
`using Stipple` creates a session folder in the current directory

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#137]
Currently Stipple creates a folder `sessions` in the current working directory when it is used or imported.
This behaviour is probably unexpected by users.
I realised this when I accidentially started Stipple for testing in C:\Windows\System32 where I didn't have write access.

Not sure how this can effectively be handled, maybe trigger folder creation upon first client access?

**Comment by AbhimanyuAryan** [comment]
I reported this to Adrian as well

**Comment by essenciary** [comment]
This has been solved with the creation of `sessions` as a temp folder by default.
