### ISSUE TITLE
Add v-bind as a macro

### ISSUE THREAD

**Issue by jochenkrattenmacher** [GenieFramework/Stipple.jl#141]
With Vue, it is possible to conditionally change an element's class/style, with v-bind: https://v2.vuejs.org/v2/guide/class-and-style.html

I find this a useful feature. As far as I can tell, Stipple currently does not provide any API for this. I thus wrote the following macro for myself:

```julia
macro v__bind(expr, type)
    :( "v-bind:$($(esc(type)))='$($(esc(expr)))'" )
end
```

an example use would be 
```julia
@v__bind("[{ active: isActive }, errorClass]", :class)
```

or 
```julia
@v__bind("{ color: activeColor, fontSize: fontSize + 'px' }", :style)
```

Happy to create a pull-request if this would be fine (I'd add a small docstring). One could also consider adding two macros instead, one called @bind_class and the other @bind_style. This may be more convenient (and equivalent, since style and class seem to be the only possible types?). Also, it may be closer to the current naming scheme of macros (which typically do not start with "v__").

**Comment by hhaensel** [comment]
Actually this can already be done with the current syntax:
```julia
:style = R"{ color: activeColor, fontSize: fontSize + 'px' }"
```
or
```julia
style! = "{ color: activeColor, fontSize: fontSize + 'px' }"
```

**Comment by hhaensel** [comment]
So can we close this?

**Comment by jochenkrattenmacher** [comment]
Guess so!
