### ISSUE TITLE
Is there any methods or labels I can do the things like v-if in vue?

### ISSUE THREAD

**Issue by Seeking-L** [GenieFramework/Stipple.jl#145]
I want to make a selection, whose option creates a input when it's chosen. So I wonder if Stipple has some functions just work like v-if.
I would be very grateful if any help could be given.

**Comment by Seeking-L** [comment]
Any methods like v-if?

**Comment by Seeking-L** [comment]
I found it.
Still thanks a lot, for authors’ work!

**Comment by essenciary** [comment]
Yes, `@iif` :) Enjoy!
