### ISSUE TITLE
How can I get the value of select?

### ISSUE THREAD

**Issue by Seeking-L** [GenieFramework/Stipple.jl#146]
I want to get the value of select.
Any type is ok, Bool Vector to show whether the options are chosen, or a String directly tells me the chosen option.
How can I make that?
Appreciate for any help!

**Comment by Seeking-L** [comment]
I found that checkbox can meet my need, but I still wonder is there any method with select.
: ) Mainly because checkbox is not as beautiful as select······

**Comment by usmcamp0811** [comment]
I am interested in this myself.. any one figure this out?

**Comment by usmcamp0811** [comment]
and then I figured it out.. 

``` julia

@reactive mutable struct FormComponent <: ReactiveModel
  value_store::R{String} = ""
  ops::R{Vector{String}} = ["processes", "web", "api", "pipelines", "scripting", "infrastructure", "db", "ml"]
end

...

select(:value_store, options=:ops)

...
```

with something like this you then just get the value from `value_store`.

**Comment by AbhimanyuAryan** [comment]
that correct @usmcamp0811 when you pick a reactive options from `ops` list. You store that value in `v-model` i.e. `value_store`
