### ISSUE TITLE
Using @in variable with same name as function's keyword argument yields "invalid keyword argument name"

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/Stipple.jl#157]
If a keyword argument is used inside the @handlers, then an @in or @out variable with the same name cannot be defined.

 Here's a MWE
````julia
using GenieFramework
@genietools 

function test(;msg="hi")
    println(msg)
end

@handlers begin
    @in msg = ""
    @onchange msg begin
        test(;msg="")
    end
end

function ui()
    [textfield("Message", :msg)]
end

@page("/", ui)
Server.isrunning() || Server.up()

````
And the error I'm getting
```julia
julia> includet("mwe.jl")
ERROR: [ Info: 2023-01-11 16:05:53 Watching ["/Users/pere/genie/demos/GenieFrameworkDemos_NewAPI/Database/mwe"]
syntax: invalid keyword argument name "__model__.msg[]" around /Users/pere/genie/demos/GenieFrameworkDemos_NewAPI/Database/mwe/mwe.jl:11
Stacktrace:
 [1] top-level scope
   @ none:1
in expression starting at /Users/pere/genie/demos/GenieFrameworkDemos_NewAPI/Database/mwe/mwe.jl:8
```

If I change the variable's name then it all works.

**Comment by hhaensel** [comment]
Just submitted a fix in #158

**Comment by hhaensel** [comment]
The latest commit even supports single keyword syntax

```julia
@handlers begin
    @in msg = ""
    @onchange msg begin
        test(; msg)
    end
end
```
@essenciary please review

**Comment by hhaensel** [comment]
@essenciary
BTW, why did you introduce `__HANDLERS__`?
I think this is not used anywhere. Perhaps you planned to collect the handlers to delete them later?
In that case, the handlers would need to be collected per model, if I'm right.

**Comment by essenciary** [comment]
@hhaensel fabulous! ♥️

`__HANDLERS__` is used extensively in `Stipple.ReactiveTools`, indeed to manage the collection of handlers.

**Comment by hhaensel** [comment]
I digged a bit deeper and I think the way you are defining `__GF_AUTO_HANDLERS__` is not as it should be.

```julia
julia> @macroexpand @handlers begin
         @in i = 1
         @onchange i begin
           println("The value of i is: ", i)
         end
       end
quote
    #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:384 =#
    isdefined(Main, :__HANDLERS__) || Core.eval(Main, $(Expr(:copyast, :($(QuoteNode(:(const __HANDLERS__ = Stipple.Observables.ObserverFunction[])))))))
    #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:386 =#
    function __GF_AUTO_HANDLERS__(__model__)
        #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:386 =#
        #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:387 =#
        empty!(__HANDLERS__)
        #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:389 =#
        begin
            #= REPL[29]:2 =#
            i = 1
            #= REPL[29]:3 =#
            begin
                #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:421 =#
                push!(__HANDLERS__, on(__model__.i) do __value__
                        #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:423 =#
                        begin
                            #= REPL[29]:4 =#
                            println("The value of i is: ", __model__.i[])
                        end
                    end)
            end
        end
        #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:391 =#
        return __model__
    end
end
```
As you see, each call of `__GF_AUTO_HANDLERS__` empties and refills `__HANDLERS__` so that `__HANDLERS__` always contain the handlers of the latest model. Furthermore, the handler contains the definitions of the model fields, which is also not the standard procedure.
I think, the `__HANDLERS__` should store expressions which are evaluated in `__GF_AUTO_HANDLERS__` in very much the same way as we do with REACTIVE_STORAGE.

Do you agree?

I've already given it a try and it works. I might prepare another PR ...

**Comment by essenciary** [comment]
Sure, if you can optimise, please go ahead. 

I don't understand "always contain the handlers of the latest model". What handlers/model should it reference?

**Comment by hhaensel** [comment]
Well, you designed `__HANDLERS__` to be module-specific, but it contains the handlers of the latest model.

**Comment by hhaensel** [comment]
There you go #159

**Comment by essenciary** [comment]
> Well, you designed `__HANDLERS__` to be module-specific, but it contains the handlers of the latest model instance.
> 
> I'd design it to contain the expressions that are needed to build `__GF__AUTO_HANDLERS__`, those are module-specific.

The assumption was one model per module at the point of writing this. So it was the same thing basically. But that changed after adding multi-model support, right?

**Comment by hhaensel** [comment]
No, the assumption was one model type per module, I was talking of model instances

**Comment by hhaensel** [comment]
With #159 we now have
```julia
julia> @handlers begin
         @in i = 1
         @in j = 2
         @in k = 3
         @onchange i, j begin
           println("The value of i is: ", i)
           println("The value of k is: ", k)
         end
       end
__GF_AUTO_HANDLERS__ (generic function with 1 method)

julia> __HANDLERS__
1-element Vector{Expr}:
 :(onany(__model__.i, __model__.j) do i, j
      #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:442 =#
      begin
          #= REPL[55]:6 =#
          println("The value of i is: ", i)
          #= REPL[55]:7 =#
          println("The value of k is: ", __model__.k[])
      end
  end)
```
Note that it is no longer necessary to have `@onchangeany`

**Comment by hhaensel** [comment]
It's even better:
```julia
julia> @macroexpand @onchange other_model.i, i begin
           println("The value of other_model.i is: ", other_model.i[])
           println("The value of i is: ", i)
           println("The value of j is: ", j)
       end
quote
    #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:459 =#
    push!(__HANDLERS__, Expr[:(onany(other_model.i, __model__.i) do _, i
      #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:453 =#
      begin
          #= REPL[84]:2 =#
          println("The value of other_model.i is: ", other_model.i[])
          #= REPL[84]:3 =#
          println("The value of i is: ", i)
          #= REPL[84]:4 =#
          println("The value of j is: ", __model__.j[])
      end
  end)]...)
end
```

**Comment by essenciary** [comment]
🤯🤩

**Comment by hhaensel** [comment]
I think, we should make HANDLERS a LittleDict just like REACTIVE_STORAGE. Only the handler function should reside in the module as it needs to have access to the module's namespace. What do you think?

**Comment by AbhimanyuAryan** [comment]
@hhaensel reading PR it's mind blowing. What's the use case for `@clear`? I am seeing we are pushing the handlers in HANDLERS as vector? `@clear` get rid of all the `HANDLERS`

Just thinking can we clear selective handlers? `@clear :user` where user is a Reactive Property on which handler is defined

Like for example I just want to get rid of handler defined on `user`

```julia
julia> for i in values(Stipple.ReactiveTools.HANDLERS)
       @info i
       end
┌ Info: Expr[quote
│     #= C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:631 =#
│     on(__model__.booking) do booking
│         #= C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:632 =#
│         #= REPL[4]:2 =#
│         booking[] += booking[] + 1
│     end
│ end, quote
│     #= C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:631 =#
│     on(__model__.user) do user
│         #= C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:632 =#
│         #= REPL[5]:2 =#
│         #= REPL[5]:2 =# @info "updating user name"
│         #= REPL[5]:3 =#
│         (__model__.user[])[] = "abhimanyu aryan"
│     end
│ end, quote
│     #= C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:631 =#
│     on(__model__.msg) do msg
│         #= C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:632 =#
│         #= REPL[9]:2 =#
│         #= REPL[9]:2 =# @info "doing"
│     end
└ end]
```

**Comment by hhaensel** [comment]
This could be done, but I'm not sure how important this is for users. Furthermore, it's not clear what should happen with the handler. If it is a specific handler with `on()` it's clear, but if it's a handler with mutliple input variables `onany()` we would need to see whether the variable is used and remove only the trigger from the list of observables.
It would require a larger refactoring, I think. I could imagine a Dict rather than a vector, but what would we do with identical set of trigger variables...

**Comment by AbhimanyuAryan** [comment]
@hhaensel yes helmut would require something like dict or something to do `O(1)` lookup. Otherwise iterating over vector would be expensive and not nice. But yes makes sense. Thanks for replying :)

**Comment by hhaensel** [comment]
> @hhaensel reading PR it's mind blowing. What's the use case for `@clear`? I am seeing we are pushing the handlers in HANDLERS as vector? `@clear` get rid of all the `HANDLERS`

`@clear` deletes REACTIVE_STORAGE and HANDLERS. The use case is interactive development of models at the REPL. We already have some ReactiveTools demos on StippleDemos.jl which are all working on the REPL. If you execute one after the other they might not work without calling `@clear`.

The new `@model` macro does clear the storage, so if we stick to that syntax in the future we won't have problems.

**Comment by AbhimanyuAryan** [comment]
thanks for explanation helmut

**Comment by hhaensel** [comment]
Should be solved, right?

**Comment by AbhimanyuAryan** [comment]
@hhaensel looks like. @PGimenez should we close?
