### ISSUE TITLE
alternative macro syntax in Stipple/StippleUI

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#172]
Currently, we have macros `@on`, `@click`. etc. which generate strings to be supplied as parameter in quasar or vue elements.
The disadvantage of this approach is that if provided as first argument they end up as content and not as parameter.
If we would change the syntax such that the macros supply kw-expressions, we can get rid of this potential source of errors.
The only thing we would have to change is that expressions need to be differently escaped.

```julia
esc_expr(expr) = :(replace($expr, '"' => "\\\""))

macro new_click(expr)
    Expr(:kw, R"@click", esc_expr(expr))
end
```
now compare the following three example lines
```julia
julia> quasar(:btn,  @click("""console.log("yes!")""")) |> println
<q-btn>v-on:click='console.log("yes!")'</q-btn>

julia> quasar(:btn,  "", @click("""console.log("yes!")""")) |> println
<q-btn v-on:click='console.log("yes!")'></q-btn>

julia> quasar(:btn,  @new_click("""console.log("yes!")""")) |> println
<q-btn @click="console.log(\"yes!\")"></q-btn>
```
BTW, it seems to be good practice to supply html paramters with double quotes and preferably use single quotes for js expressions. Then we would rather write
```julia
julia> quasar(:btn,  @new_click("console.log('yes!')")) |> println
<q-btn @click="console.log('yes!')"></q-btn>
```
@essenciary , @AbhimanyuAryan
In case that you agree, I'd rewrite all macros of this type.

**Comment by essenciary** [comment]
@hhaensel 
I see this as a more generic issue about adding events to elements in an intuitive and consistent manner. 

How do we pass the content into the elements with the new macro? 

Re double and single quotes, for Genie HTML templates the recommendation is using single quotes for HTML attributes (I don't remember exactly why though, but it has to do with escaping double quotes - I can check, but it would help the users to keep it consistent to reduce mental overload).

**Comment by hhaensel** [comment]
> How do we pass the content into the elements with the new macro?

The macro only changes the way, how attributes are passed by macros. Content specification is as before by first positional argument and by arrays.
```julia
julia> quasar(:hh,  "content 1", @new_click("console.log('yes!')"), ["content 2"]) |> println
<q-hh @click="console.log('yes!')">content 1content 2</q-hh>
```
> Re double and single quotes, for Genie HTML templates the recommendation is using single quotes for HTML attributes (I don't remember exactly why though, but it has to do with escaping double quotes - I can check, but it would help the users to keep it consistent to reduce mental overload).

Most HTML guides that I found point out that there is no better or worse of using outer single or double quotes.

What I found convincing is the following statement from https://stackoverflow.com/questions/242813/are-double-and-single-quotes-interchangeable-in-javascript

> There is no one better solution; however, I would like to argue that double quotes may be more desirable at times:
> 
> - Newcomers will already be familiar with double quotes from their language. In English, we must use double quotes " to identify a passage of quoted text. If we were to use a single quote ', the reader may misinterpret it as a contraction. The other meaning of a passage of text surrounded by the ' indicates the 'colloquial' meaning. It makes sense to stay consistent with pre-existing languages, and this may likely ease the learning and interpretation of code.
>
> 
> - Double quotes eliminate the need to escape apostrophes (as in contractions). Consider the string: "I'm going to the mall", vs. the otherwise escaped version: 'I\'m going to the mall'.
> Double quotes mean a string in many other languages. When you learn a new language like Java or C, double quotes are always used. In Ruby, PHP and Perl, single-quoted strings imply no backslash escapes while double quotes support them.
> 
> - JSON notation is written with double quotes.

But with 
```julia
esc_expr(expr) = :(Stipple.JSONText("'" * replace("$($expr)", ''' => "\\\'") * "'"))
```
we could also implement single quotes.

**Comment by hhaensel** [comment]
I merged both Stipple and StippleUI.

@essenciary , @AbhimanyuAryan are you going to test before we release this?
I released a separate version with the fixes for #174.

**Comment by AbhimanyuAryan** [comment]
Sorry for the delay @hhaensel will test tonight or first thing tomorrow morning

**Comment by hhaensel** [comment]
Fine for me. The changes will probably not affect applications with html views but rather applications that rely on StippleUI

**Comment by AbhimanyuAryan** [comment]
@PGimenez can you test all you new API demos with Stipple master? Would be great help

**Comment by hhaensel** [comment]
Yesterday evening I added the macro changes as agreed. And I changed dictionary parsing, as there were ambiguous definitions.
