### ISSUE TITLE
Displaying math equations

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/Stipple.jl#177]
I have a running simulation where I can change its parameters, and I'd like to display the equations with the updated parameters.  I see that there's a [StippleLatex.jl package](https://github.com/GenieFramework/StippleLatex.jl), but can't find any example code. Is there any recommended way to display math equations?

https://github.com/GenieFramework/GenieFrameworkDemos_NewAPI/tree/main/SystemSimulation
![ezgif-3-5228b2f77f](https://user-images.githubusercontent.com/5058397/219419068-54499fb2-1972-49fd-80be-6aebdbfec074.gif)

**Comment by PGimenez** [comment]
Thanks @hhaensel. Sttill, can't try it because there is a version conflict for Genie between GenieFramework and StippleLatex:

```julia
(SystemSimulation) pkg> add StippleLatex
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Genie [c43c736e]:
 Genie [c43c736e] log:
 ├─possible versions are: 0.9.4-5.15.0 or uninstalled
 ├─restricted by compatibility requirements with Reexport [189a3867] to versions: 1.10.0-5.15.0 or uninstalled
 │ └─Reexport [189a3867] log:
 │   ├─possible versions are: 0.2.0-1.2.2 or uninstalled
 │   └─restricted to versions 1 by DifferentialEquations [0c46a032], leaving only versions 1.0.0-1.2.2
 │     └─DifferentialEquations [0c46a032] log:
 │       ├─possible versions are: 7.7.0 or uninstalled
 │       └─DifferentialEquations [0c46a032] is fixed to version 7.7.0
 ├─restricted by compatibility requirements with GenieFramework [a59fdf5c] to versions: 5.0.0-5.15.0
 │ └─GenieFramework [a59fdf5c] log:
 │   ├─possible versions are: 1.0.0-1.9.0 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 1.0.0-1.9.0
 └─restricted by compatibility requirements with StippleLatex [8706c442] to versions: 1.0.0-3.3.0 — no versions left
   └─StippleLatex [8706c442] log:
     ├─possible versions are: 0.1.0-0.3.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.3.0

```
will try to fix this

**Comment by essenciary** [comment]
I tagged a new release v0.8 for StippleLatex. Some updates might be necessary though. Try it and lmk @PGimenez

**Comment by hhaensel** [comment]
Yip, needs small updates. Do I have the rights to merge?

**Comment by hhaensel** [comment]
I think the API needs a little overhaul, maybe find the time tonight.
My first idea would be to define string macros with modifiers that serve expressions as `@on`

**Comment by PGimenez** [comment]
Even if we update the versions, there are still errors. I'd opened an issue on the stipplelatex repo

https://github.com/GenieFramework/StippleLatex.jl/issues/10

**Comment by PGimenez** [comment]
done in https://github.com/GenieFramework/StippleLatex.jl/issues/10

**Comment by AbhimanyuAryan** [comment]
@PGimenez what does it look like? Any update `.gif` 😀?

**Comment by hhaensel** [comment]
There's still aproblem with the Auto mode ...

**Comment by hhaensel** [comment]
`v-katex:auto`
is not yet implemented as it should, but even if I enter the correct syntax by hand I receicejs errors.
It seems that the vue-katex.min.js is not correctly built.

**Comment by hhaensel** [comment]
KaTex, which is used for displaying LaTeX, supports an auto mode, where certain text delimiters indicate LaTeX content, e.g.
```
span(latex"This is auto mode with an inline formula \(\cos^2x\) and a display formula $$\sin^2x$$"auto)`
```
is rendered as 
![image](https://user-images.githubusercontent.com/31985040/220577691-c6a48fcf-0853-4ef3-972f-98806a5976fb.png)

**Comment by AbhimanyuAryan** [comment]
got it

**Comment by hhaensel** [comment]
Very convenient, particularly for writing `'` characters, which are not supported in literal expression in normal mode.

**Comment by hhaensel** [comment]
Got it all working, updated the Readme, have a look!
Will tag now.

**Comment by AbhimanyuAryan** [comment]
sounds great @hhaensel checking ...
