### ISSUE TITLE
How can I change the "loading" of a btn?

### ISSUE THREAD

**Issue by Seeking-L** [GenieFramework/Stipple.jl#179]
I made a btn like this:

    btn1 = btn("START!", loading=false,
        color="brand",
        textcolor="white",
        size="15px",
        @click("value += 1"),
        [
            tooltip(contentclass="bg-indigo",
                contentstyle="font-size: 16px",
                style="offset: 1000px 1000px",
                "Click it!"
            )
        ]
    )

When I click it ,something will happen, and I want the "loading" to be true. How can I do that?

**Comment by hhaensel** [comment]
You need to have a boolean field, e.g. `:mybutton` in your model and trigger your action via this field.
```julia
@app
    @in mybutton = false
    @in value

    @onbutton mybutton begin
        value += 1
        < here is the code that takes a while >
    end
end

function ui()
    btn("Click here to do some magic action", loading = :mybutton, @click(:mybutton))
end
```

**Comment by Seeking-L** [comment]
I got that!   And I also learnt a lot in the forums you mentioned in another issue. 
Thank you so much!

**Comment by hhaensel** [comment]
You're welcome 😃
