### ISSUE TITLE
How to make a alert just like alert="" in js?

### ISSUE THREAD

**Issue by Seeking-L** [GenieFramework/Stipple.jl#180]
I want to set a alert, how can I do this?
In addition, how can I insert a piece of js/html code in my page?
Thanks!

**Comment by hhaensel** [comment]
@Seeking-L 
We understand that documentation of Stipple is still behind its functionality. Nevertheless, the issue section in Github is not meant to be a support forum, although we have offered help through this channel every now and then. But in general such questions are better supported in [Discord](https://discord.com/invite/9zyZbD6J7H) , [discourse](https://discourse.julialang.org/) or [stackoverflow](https://stackoverflow.com/). Furthermore, StipplpeDemos.jl is a good place to find example code for various applications.

Please come back here for reporting bugs or missing functionality (if you have checked that it is really missing 😉)

Finally, I won't let you go without providing some help.
- Notifications to the model are sent via `notify(model, "Hi from my first Stipple app")` if you write the handlers 'by hand' or via `@notify "Hi from my first app"` in the `@handlers` macro of the new reactive API.
- executing js code is achieved vie `run(model, "console.log('hello from the backend')")` It is documented in the doc string of `run` after loading Stipple.
```
  function Base.run(model::ReactiveModel, jscode::String; context = :model)

  Execute js code in the frontend. context can be :model, :app or :console
```

**Comment by Seeking-L** [comment]
Thanks a lot! I just didn't know about the places above , now I get it! 
And I'm sorry to bother you...
Thanks to all contributors！

**Comment by hhaensel** [comment]
No problem, I'm also active in the above places 😉
