### ISSUE TITLE
Output not updated when interpolating Julia code in view

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/Stipple.jl#184]
I'm trying to show the output of a calculation in an html file. I've tried with the three possibilities for Julia code interpolation but only `{{}}` works. 
This is a MWE
```julia
module App
using GenieFramework
@genietools

@app begin
    @out result = 3.14
    @in mult = 1.0
    @onchange mult begin
        result = 3.14 * mult
    end
end

@page("/", "mwe.html")
Server.up()
end
```

```html
<q-input label="Multiplier" v-model="mult"> </q-input>
{{result}} <br>
$(result) <br>
<% result %> <br>
```
This shows that only the `{{}}`output is updated
![Untitled](https://user-images.githubusercontent.com/5058397/225950373-32a2dd2f-c4ac-4cab-952a-c201c06069ff.gif)

I could just use `{{}}` even if the other syntaxes don't update, but I want to round the result. For some reason, functions can't be called from within `{{}}`. If I try to round the result variable,

```html
{{round(result)}} <br>
$(result) <br>
<% result %> <br>
```
the page renders for a split second and then disappears. The logs don't show any hint.
![Untitled2](https://user-images.githubusercontent.com/5058397/225951698-0c75bc25-3d23-44d7-b629-55a02c6f92ce.gif)

**Comment by hhaensel** [comment]
There are several reasons for the behavior.
- mustache bracketing is the correct form for dynamic interpolation `{{ <javascript expression> }}`
- `$result` is Julia string interpolation and is only executed on compilation of the html code of the page
- `<% result %>` is the Genie way of interpolating html code with julia expressions. Again this is only done once for building the html code.

So only version 1 is ecpected to dynamically change upon change of input.

The story with `round(result)` is different but simple. In Javascript rounding is achieved by `Math.round()`, so `{{ Math.round(result) }}` should do the job.

**Comment by PGimenez** [comment]
I see, didn't know the mustaches only accepted Javascript. I'll do the rounding in the Julia code then, this just a simple example and would rather not have people write Javascript. Thanks!
