### ISSUE TITLE
Configurable Debounce per field

### ISSUE THREAD

**Issue by Eldalie** [GenieFramework/Stipple.jl#186]
Having a default debounce functionality is essential, but applying to all fields can slow down the app.
By example: the "isready" field only slows down page loading as "isready" is called only once.

So we have to find a way to make debounce configurable per field.

For now debounce is deactivated for "isready" : see https://github.com/GenieFramework/Stipple.jl/pull/181

**Comment by hhaensel** [comment]
Done!
isready is already without debouncing per default. other fields can now be added
```julia
@debounce myfield 0

@debounce x, y, z 10
```

**Comment by hhaensel** [comment]
@Eldalie please check and close if your requirement is met

**Comment by Eldalie** [comment]
Thank you !  However, I've moved on to another project since then, and unfortunately, I seem to have lost my old code. I trust that you did your best !
