### ISSUE TITLE
Mutating @in/out variable on a route call

### ISSUE THREAD

**Issue by svilupp** [GenieFramework/Stipple.jl#190]
How would I access/mutate a variable in the reactive model when a route is called?

Use cases: Let's say I want to know whether a user has visited a certain page or I want to know whether a form was submitted (POST method), etc.

Toy demo: 
- Let's take the [Iris dashboard](https://github.com/GenieFramework/GenieFrameworkDemos_NewAPI/blob/main/IrisClusteringNewAPI/dashboard.jl)
- I would like to change the reactive model variable `no_of_clusters` when route "/clusters3" gets called to =3
- All listeners get triggered (to make relevant updates
- User gets redirected back to main page (route `:get`)

My snippet:
```
route("/clusters3") do
    stored_model = GenieSession.get(:Main_ReactiveModel, nothing)
    if !isnothing(stored_model)
        stored_model.no_of_clusters[] = 3
    end
    redirect(:get)
end
```

My mental model for Stipple:
- ReactiveModel (=RM) is a storage template, handlers are Observables listeners
- When I initialize the RM inside of some route (eg, with `model=@init` or implicitly via `@page`), it creates a session-local copy of that storage; It inherits all listeners (handlers) and is set to default values for the RM
- I can access that storage (once initialized) like this `stored_model = GenieSession.get(:Main_ReactiveModel, nothing)` (where `:Main_ReactiveModel` is the auto-generated name that you can find in `Stipple.ReactiveTools.TYPES[Main]` if you evaluated in Main module)
- Once the `stored_model` is available, I can change the properties however I want, as it's indistinguishable from other changes (it's all observables)

**My questions:**
- Is such usage okay? `GenieSession.get` feels like a low-level intervention
- Is there a better way to update a property of the RM (without having one global model shared by all visitors)

**Comment by PGimenez** [comment]
I think you got it all right. From what I've been told, each user (each request) gets an instance of the model with their values - so it's only accessible in the context of a request or `@onchange`. If you want to access it anywhere else then you'd need to reference it from a global var at some outer scope.

Here's a MWE to illustrate this. Accessing `/test´will show `test!`. Opening a new browser tab and accessing `/global`will show `global!`on this route and also in the previous tab opened at `/test`. Indeed, the model is global and shared by all routes.

```julia
module App
using GenieFramework, Stipple
@genietools

@app begin
    @out message = "Hello!"
    @onchange isready begin
        @show "App is loaded"
        @show __model__
    end
end

route("/test") do
    global model = @init
    @show "Test route"
    @show model
    Stipple.update!(model, :message, "test!", "")
    page(model, ui()) |> html
end

route("/global") do
    @show "Global route"
    Stipple.update!(model, :message, "global!", "")
    page(model, ui()) |> html
end

ui() = "{{message}}"

@page("/", ui)
Server.up(8000)
end
```

**Comment by svilupp** [comment]
Thank you. 

Do I understand correctly that "model" in your example is global, ie, shared across all users/sessions?

What if you wanted to set some user-specific preferences? That's why I've used in GenieSession in my snippet to access the session-specific instance of the model. Is there a better way to access the instantiated reactive model?

**Comment by hhaensel** [comment]
I think you have quite a good understanding of the architecture.
In the example every  accessing of /test generates a new model. Any access of /global refers to the most recent model.

**Comment by hhaensel** [comment]
Some more thoughts on this:

There is `Stipple.ModelStorage.Sessions` which includes ìnit_from_storage()`.
That function initialises a model and attaches a handler that will pass the stored values to the model as soon as the client is ready.
The macro `@init` will take init_from_storage() if it is available. So the only thing you need to add is

```julia
using Stipple.ModelStorage.Sessions
```
in order to have your model initialised with the stored values. If you want to change values of the model manually during the route call, you can do that, prefereably by using silent assignment:
```julia
route("/global") do
    model = @init
    # the exclamation mark means that no listeners are triggered, so no update to the client will be tried at that time
    model.message[!] = "global, silent: $(rand(1:9))"
    # alternatively, if you have listeners attached that should be triggered, you can do
    model.message[] = "global, all triggers are called"
    page(model, ui()) |> html
end
```
In the second case, all triggers will be called, particularly the one that will try to update the client. In former times that produced an error, but I think now we only return a false, when the client could not be reached.

**Comment by svilupp** [comment]
Apologies, I forgot to close the issue! The above-suggested solution works like a charm! Thank you.
