### ISSUE TITLE
precompile of GB-project fails: "some other module mutating `Stipple` with `eval` during precompilation - don't do this."

### ISSUE THREAD

**Issue by michaelfliegner** [GenieFramework/Stipple.jl#194]
I want to deploy my Genie Builder Project to julia hub. Precompile fails with error below.
Source is
https://github.com/Actuarial-Sciences-for-Africa-ASA/GenieBuiltLifeProto
You can, however,  **run** the app - in gitpod, for example, with a preloaded postgres db.
by 
```
include("run.jl")
```

Code is developped with and runs under GenieBuilder, all I changed is, add this module
https://github.com/Actuarial-Sciences-for-Africa-ASA/GenieBuiltLifeProto/blob/main/src/GenieBuiltLifeProto.jl
```
Failed to precompile GenieBuiltLifeProto [9e6ec31a-4cef-4def-9440-f7db695aa5a5] to /home/gitpod/.julia/compiled/v1.8/GenieBuiltLifeProto/jl_VjC2Gc.
ERROR: LoadError: Evaluation into the closed module `Stipple` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Stipple` with `eval` during precompilation - don't do this.
Stacktrace:
 [1] eval
   @ ./boot.jl:368 [inlined]
 [2] binding(expr::Expr, m::Module, mode::Any; source::LineNumberNode, reactive::Bool)
   @ Stipple.ReactiveTools ~/.julia/packages/Stipple/XoQ2b/src/ReactiveTools.jl:274
 [3] var"@out"(__source__::LineNumberNode, __module__::Module, expr::Any)
   @ Stipple.ReactiveTools ~/.julia/packages/Stipple/XoQ2b/src/ReactiveTools.jl:361
 [4] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [5] include(x::String)
   @ GenieBuiltLifeProto /workspace/GenieBuiltLifeProto/src/GenieBuiltLifeProto.jl:1
 [6] top-level scope
   @ /workspace/GenieBuiltLifeProto/src/GenieBuiltLifeProto.jl:6
 [7] include
   @ ./Base.jl:419 [inlined]
 [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [9] top-level scope
   @ stdin:1
in expression starting at /workspace/GenieBuiltLifeProto/app.jl:26
in expression starting at /workspace/GenieBuiltLifeProto/app.jl:1
in expression starting at /workspace/GenieBuiltLifeProto/src/GenieBuiltLifeProto.jl:1
in expression starting at stdin:1
```

**Comment by hhaensel** [comment]
Not sure whether that solves it (currentlyon my mobile), but try to replace `@handlers` by `@app`

**Comment by michaelfliegner** [comment]
Will try that this evening. Thankful for your quick response🙏

**Comment by michaelfliegner** [comment]
Unfortuantely, that wasn´t it: error remains:

(GenieBuiltLifeProto) pkg> precompile
Precompiling project...
  ✗ GenieBuiltLifeProto
  0 dependencies successfully precompiled in 43 seconds. 216 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

GenieBuiltLifeProto [9e6ec31a-4cef-4def-9440-f7db695aa5a5]

Failed to precompile GenieBuiltLifeProto [9e6ec31a-4cef-4def-9440-f7db695aa5a5] to /home/gitpod/.julia/compiled/v1.8/GenieBuiltLifeProto/jl_dX4Zu3.
ERROR: LoadError: Evaluation into the closed module `Stipple` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Stipple` with `eval` during precompilation - don't do this.
Stacktrace:
 [1] eval
   @ ./boot.jl:368 [inlined]
 [2] binding(expr::Expr, m::Module, mode::Any; source::LineNumberNode, reactive::Bool)
   @ Stipple.ReactiveTools ~/.julia/packages/Stipple/XoQ2b/src/ReactiveTools.jl:274
 [3] var"@out"(__source__::LineNumberNode, __module__::Module, expr::Any)
   @ Stipple.ReactiveTools ~/.julia/packages/Stipple/XoQ2b/src/ReactiveTools.jl:361
 [4] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [5] include(x::String)
   @ GenieBuiltLifeProto /workspace/GenieBuiltLifeProto/src/GenieBuiltLifeProto.jl:1
 [6] top-level scope
   @ /workspace/GenieBuiltLifeProto/src/GenieBuiltLifeProto.jl:6
 [7] include
   @ ./Base.jl:419 [inlined]
 [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [9] top-level scope
   @ stdin:1
in expression starting at /workspace/GenieBuiltLifeProto/app.jl:26
in expression starting at /workspace/GenieBuiltLifeProto/app.jl:1
in expression starting at /workspace/GenieBuiltLifeProto/src/GenieBuiltLifeProto.jl:1
in expression starting at stdin:1

(GenieBuiltLifeProto) pkg>

**Comment by hhaensel** [comment]
Will try to have a look tonight.

**Comment by hhaensel** [comment]
I just published a branch hh-precompile to address the issue.
Would you be so kind and test with that branch?
```julia
] add Stipple#hh-precompile
```

**Comment by hhaensel** [comment]
When I wrote this I was just learning about macro programming and was not aware about this kind of dos and don'ts.
Meanwhile I am, although I am still learning...

**Comment by michaelfliegner** [comment]
I am on stand-by

**Comment by hhaensel** [comment]
There's more to it, I'll let you know when there are essential news.

**Comment by michaelfliegner** [comment]
Mille grazie

hhaensel ***@***.***> schrieb am Di., 2. Mai 2023, 08:34:

**Comment by hhaensel** [comment]
You can try now. I built a MWE for myself and that passes with two warnings. The warnings result from the fact that we allow for redefinition of apps, so they are there by design.

**Comment by michaelfliegner** [comment]
will You close the issue after merging into the main branch?

**Comment by hhaensel** [comment]
Happy that it works for you as well. Have you also tested functionality?

**Comment by michaelfliegner** [comment]
ja, läuft.
