### ISSUE TITLE
Precompiling your app with PrecompileTools

### ISSUE THREAD

**Issue by svilupp** [GenieFramework/Stipple.jl#198]
Do we have any guides or tutorials for how to improve the startup times of Stipple apps?

I'm thinking about the context of Julia 1.9 + PrecompileTools, but I'm not sure how to effectively execute most of the required routes.

I think a good pattern might be the [PrecompileTools/Startup.jl](https://julialang.github.io/PrecompileTools.jl/stable/#Tutorial:-local-%22Startup%22-packages).

**Comment by svilupp** [comment]
I can confirm that the PrecompileTools workflow works nicely. I'll add mini example and some timings later.

**Comment by svilupp** [comment]
In short, I followed the guide [here](https://julialang.github.io/PrecompileTools.jl/stable/#Tutorial:-local-%22Startup%22-packages). 

Steps:
- Create an entry point for your dashboard (eg, file "dashboard.jl")
- Create a new package inside the same folder (eg, "DashboardPrecompile" below)
- Inside the new package module, add a `@compile_workload` statement that calls your dashboard and then shuts it down (eg, `include("dashboard.jl"); Server.down()`)
- Then jump back to your dashboard environment and add dev dependency for the precompilation bundle (eg, `]dev DashboardPrecompile`)
- Run it and feel the speed (requires Julia 1.9 to make a difference)

More detailed MWE:

"dashboard.jl" (a simple Stipple app)
```
using GenieFramework
@genietools

@time begin
  @app begin
    @in title = "My First App"
    @in select_number = 0.5
    @in selected_item = Symbol("x")
    @out options_item = [:x, :y, :z]
    @out output_text = "Hello World"
    @onchange isready, selected_item, select_number begin
      output_text = "You selected: $selected_item and $select_number"
    end
  end

  function ui()
    [
      heading("{{title}}")row([
        cell(class="st-module", [
          h6("Text Input"),
          textfield(class="q-my-md", "Input", :input, hint="Please enter some words")
        ])
        cell(class="st-module", [
          h6("Slider"),
          slider(0.0:0.01:1.0, :target_quantile; name="NOT WORKING YET", label=true)
        ])
        cell(class="st-module", [
          h6("Select"),
          Stipple.select(:selected_item; options=:options_item)
        ])
      ])row([
        cell(
          class="st-module",
          [
            h3("Output"),
            br(),
            span("{{output_text}}")
          ]
        )
      ])
    ]
  end

route("/") do
    model = @init
    page(model, ui()) |> html
  end

  Server.isrunning() || Server.up(8000)
end
```

Then in Julia REPL, I created a new package DashboardPrecompile in the same folder as my `dashboard.jl`:
`]generate DashboardPrecompile`
And I modify the `DashboardPrecompile/src/DashboardPrecompile.jl` with the following:
```
module DashboardPrecompile

using PrecompileTools

@compile_workload begin
    ## run the dashboard (async!)
    include(joinpath(@__DIR__, "..", "..", "dashboard.jl"))
    sleep(1)
    ## hit all get routes
    get_routes = filter(Genie.Router.routes()) do route
        ## skip any dev / internal routes
        route.method == "GET" && !(occursin("genie", string(route.name)) || occursin("devtools", string(route.path)))
    end
    for route in get_routes
        route.action()
    end
    sleep(1)
    Server.down()
end
end # End module 
```
Make sure to copy your deps from the dashboard into the Project.toml of the DashboardPrecompile. Mine looked like this: 
"DashboardPrecompile/Project.toml"
```
name = "DashboardPrecompile"
uuid = "608eb7fb-c9cd-4a54-8d3f-4d2db9968ada"
authors = ["xxx"]
version = "0.1.0"

[deps]
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
GenieFramework = "1.18"
```

**Comment by svilupp** [comment]
It seems that a chunk of the invalidation leading to the slow import is coming from StipplePlotly:

```
inserting convert(::Type{Vector{<:StipplePlotly.Charts.PlotData}}, dd::Vector) @ StipplePlotly.Charts ~/.julia/packages/StipplePlotly/1ZRLM/src/Charts.jl:955 invalidated:
   backedges: 1: superseding convert(::Type{T}, a::AbstractArray) where T<:Array @ Base array.jl:613 with MethodInstance for convert(::Type{<:Vector}, ::Vector{A} where {T, A<:AbstractVector{T}}) (9 children)
              2: superseding convert(::Type{T}, a::AbstractArray) where T<:Array @ Base array.jl:613 with MethodInstance for convert(::Type{<:Vector}, ::Vector) (376 children)
```
The offending line is [here](https://github.com/GenieFramework/StipplePlotly.jl/blob/de0a3ddc7b026ae5dcd83739f0a5ee3c027fedaf/src/Charts.jl#L955) invaliding almost 400 methods.

Out of curiosity, I replaced `using GenieFramework` just with Genie, Stipple, StippleUI (since I don't need StipplePlotly) and it speeds up the precompiled version to start in 1.6s (the non-precompiled version stays at 2.2s)

**Comment by hhaensel** [comment]
That's a good find. We should definitely replace that by stippleparse. It's from the early times of Stipple

**Comment by hhaensel** [comment]
Just fixed it in master and currently being released. Feel free to test and report potential improvements.

**Comment by svilupp** [comment]
Amazing! I look forward to testing it out!

**Comment by svilupp** [comment]
Updated timing (w/ StipplePlotly#main):
- Julia 1.9: - / 1.5s / 0.22s / 0.25s = 1.97s
- Julia 1.9 + PrecompileTools: 1.64s / 0.08s / 0.13s / 0.01s = 1.86s

So it gets us below 2s and precompile tools start to have an effect:) 

I wonder how much of a delta it is on more serious dashboards (GermanCredit/Iris/etc.)

**Comment by svilupp** [comment]
Just FYI - I tried it on GermanCredit dashboard and almost halves the time needed. That's without precompiling the actual loading of the homepage (sending a GET call), which could be even more significant.

**Comment by hhaensel** [comment]
Thanks for the updated timings. It was a short thing to rename the functions. It took a little more time to discover the root cause of increased compiling times, which came with julia 1.9.
Seemingly broadcasting over large tuples shows increased compile times and can be worked around by converting tuples to arrays.
So I took a good piece of learning from this issue.
Thanks for raising it.

**Comment by hhaensel** [comment]
@svilupp If you happen to find more bottlenecks in Stipple/Genie we are happy to receive more issues from you.

**Comment by svilupp** [comment]
Nothing specific to Genie ecosystem, but there are many invalidations coming from the upstream packages. I’ve opened [a thread on Discourse](https://discourse.julialang.org/t/fixing-invalidation-what-would-an-expert-do/98484) to understand how to tackle them
