### ISSUE TITLE
scope of macros (@data, @bind, etc.)

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#20]
I have a string variable, say `opts = "myopts"` and I want to have the content linked to a field of an element.

I first tried 
```
slider(..., option=@data("$opts"), ...)
```
However, this fails, because the `@data` macro is not executed in the `Main` module, but in `Stipple.Elements`. Also feeding variables does not work for the same reason.

In order for this to work, `expr` must be escaped:
```
macro data(expr)
  :( Symbol($(esc(expr))) )
end
```

Analogously, also the other macros would need to retrieve some escaping treatment, e.g.
```
macro click(expr)
    :( "@click='$(startswith(string($(esc(expr))), ":") ? string($(esc(expr)))[2:end] : $(esc(expr)))'" )    
end
```

Example with the proposed changes:

```
julia> opts = "myopts";
julia> @data("$opts")
:myopts
julia> @data(opts)
:myopts
julia> @click(opts)
"@click='myopts'"
```

@essenciary : Should I make these changes or submit a PR?

(Btw, I have not understood, why you suppress a leading colon, as `string(:test)=="test"`. If you have some argument that needs to start with a colon, then you would have to supply it twice)

**Comment by hhaensel** [comment]
I'd go with the following definition
```
macro click(expr)
   :( "@click='$($(esc(expr)))'" )
end
```

```
julia> @click(opts)
"@click='myopts'"

julia> @click(:test)
"@click='test'"

julia> @click(":test")
"@click=':test'"
```

**Comment by hhaensel** [comment]
The old version would allow the following usage:
```
@on(click, console.log("Hello World"))
```
But I think this is not very Julian, and it would fail at
```
@on(click, console.log("Hello World"); alert("me"))
```
The proposed variant would accept
```
@on(:click, """console.log("Hello World"); alert("me")""")
```
In order to also accept
```
@click("console.log('Hello World'); alert('me')")
```
we would need to escape the simple quotes
```
macro click(expr)
  :( "@click='$(replace($(esc(expr)),"'" => raw"\'"))'" )
end

macro on(args, expr)
  :( "v-on:$(string($(esc(args))))='$(replace($(esc(expr)),"'" => raw"\'"))'" )
end
```

**Comment by hhaensel** [comment]
@essenciary Shall I apply these changes?

**Comment by essenciary** [comment]
@hhaensel 
1. it is removing the starting column as I can not replicate your output. In my case, the starting column for symbols it kept, and it should not be outputted in JS. 

Ex: 
```julia
julia> macro foo(expr)
       string(expr)
       end
@foo (macro with 1 method)

julia> @foo :foo
":foo"
```

2. It makes sense to allow passing JS strings, for sure. Wondering if it's better to define a `@js` helper instead which might allow us to do processing right there, instead of adding the logic in each handler? It would also be a nice syntactical sugar, I think, and we could do fancier things with it (eg add JS parsing in VS code).

**Comment by hhaensel** [comment]
> 1. it is removing the starting column as I can not replicate your output. In my case, the starting column for symbols is kept, and it should not be outputted in JS.

I see, this problem does not occur for escaped epressions 😃, moreover, the string in the on-macro can be eliminated. 

```
macro on(args, expr)
    :( "v-on:$($(esc(args)))='$(replace($(esc(expr)),"'" => raw"\'"))'" )
end
```

> 2. Wondering if it's better to define a @js helper instead 

Maybe, this can too easily be confused with other js-macros which are already around. In this particular case, only the simple quotes need to be escaped. And currently I only see these two applpications.

**Comment by essenciary** [comment]
1. awesome! 😎
2. agreed 👍 we can introduce `@js` at some other time, if needed
