### ISSUE TITLE
how to build a navbar?

### ISSUE THREAD

**Issue by alerem18** [GenieFramework/Stipple.jl#200]
i want a navbar like home, about us, contact us, i want to customize it's style and also click on each of those and change current url
and if it's possible use reactive changing urls in SPA
i know one way is using lists, but i don't see nav element in stippleUI, also i don't know how tab component works or tapgroup because i don't know how to use target url there

**Comment by essenciary** [comment]
Good point, thanks for raising this. Let us take a look and see what we can do. @AbhimanyuAryan @PGimenez

**Comment by hhaensel** [comment]
That's, in principal, possible with the QToolbar.
If you work with StippleUI this element is available via `toolbar()` and a first example is given in the doc string (`?toolbar`).
However, if it comes to SPA, you will probably want to use the Vue router, which we currently do not support. But you can build several apps which all use the same navbar. Or you can use the same model with different UIs for different routes.
