### ISSUE TITLE
layout doesn't render quasar components

### ISSUE THREAD

**Issue by alerem18** [GenieFramework/Stipple.jl#205]
this works 
```julia
layout([
  span("hi")
], model; title="layout")
```

but not this
 
```julia
layout([
  btn("hi")
], model; title="layout")
```

**Comment by hhaensel** [comment]
What are you expecting or what does not work?

**Comment by hhaensel** [comment]
`btn()` is a quasar component that is only rendered in the context of a quasar page. There is also `button()` that displays an unstyled button without further layout properties.

**Comment by alerem18** [comment]
so we are not able to use quasar components on layout right?
