### ISSUE TITLE
Loading Stipple affects convertion of JSON3.Dict into Dict

### ISSUE THREAD

**Issue by jeremiedb** [GenieFramework/Stipple.jl#214]
After loading Stipple package, the behavior of conversion of a `JSON3.Dict` object into a `Dict` is changed such as the type of keys changes from `Symbol` to `String`. 

Original behavior:

```julia
using JSON3

data = Dict(
    :hello => 1.1,
    :hi => 2.2)

JSON3.write("test.json", data)

julia> raw = JSON3.read("test.json")
JSON3.Object{Vector{UInt8}, Vector{UInt64}} with 2 entries:
  :hi    => 2.2
  :hello => 1.1

julia> dict = Dict(raw)
Dict{Symbol, Any} with 2 entries:
  :hi    => 2.2
  :hello => 1.1
```

Modified behavior:

```julia
using JSON3
using Stipple

data = Dict(
    :hello => 1.1,
    :hi => 2.2)

JSON3.write("test.json", data)

julia> raw = JSON3.read("test.json")
JSON3.Object{Vector{UInt8}, Vector{UInt64}} with 2 entries:
  :hi    => 2.2
  :hello => 1.1

julia> dict = Dict(raw)
Dict{String, Any} with 2 entries:
  "hi"    => 2.2
  "hello" => 1.1
```

The above change in the type of Dict keys seems like an undesirable side effect. 
I first thought it may be related to `StructTypes`, but only loading that package instead of `Stipple` still keeps the Dict keys as symbols.

**Comment by hhaensel** [comment]
Good finding. It's related to Genie, though.
```julia
julia> jd = JSON3.write(data) |> JSON3.read
JSON3.Object{Base.CodeUnits{UInt8, String}, Vector{UInt64}} with 2 entries:
  :hi    => 2.2
  :hello => 1.1

julia> Dict(jd)
Dict{Symbol, Any} with 2 entries:
  :hi    => 2.2
  :hello => 1.1

julia> using Genie

julia> Dict(jd)
Dict{String, Any} with 2 entries:
  "hi"    => 2.2
  "hello" => 1.1
```
typing
```julia
julia> Dict(jd,
```
plus TAB key reveals the culprit
```julia
Dict(o::JSON3.Object) @ Genie.Router C:\Users\helmu\.julia\packages\Genie\XpFvB\src\Router.jl:832
```
It is definitely type piracy and should be removed. Are you going to raise this in Genie or should I do it?

**Comment by hhaensel** [comment]
It's fixed in Genie. I propose, we leave this open until the next Genie version is registered.

**Comment by essenciary** [comment]
@hhaensel I tagged a new Genie version yesterday: https://github.com/GenieFramework/Genie.jl/releases/tag/v5.18.2

**Comment by essenciary** [comment]
I confirm that the issue has been solved per my tests - closing.
