### ISSUE TITLE
Why does @mixin only work for named models?

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/Stipple.jl#216]
I'm trying to use the @mixing macro to extend the reactive model with fields from a struct. However, this only works when using a named model. For instance, this code will throw `ERROR: UndefVarError: `field` not defined`

```julia
using GenieFramework
@genietools

@kwdef struct mixstruct
    field::R{Bool} = false
end

@app begin
    @out var1 = 0
    @mixin mixstruct
    @onbutton field begin
        println("button clicked")
    end
end

function ui()
    btn("TEST", @click("field = true"))
end
@page("/", ui)

```
If I remove the @onbutton handler then the code runs fine, and if I inspect the model with `@init`it does indeed have the `field`from `mixstruct`appended.

On the other hand, this code works with no issues

```julia
using GenieFramework
@genietools

@kwdef struct mixstruct
    field::R{Bool} = false
end

@app Model begin
    @out var1 = 0
    @mixin mixstruct
    @onbutton field begin
        println("button clicked")
    end
end

function ui()
    btn("TEST", @click("field = true"))
end

route("/") do
   model = Model |> init |> handlers
   page(model, ui())
end

```

I've been looking at the code for `@page`, `@handler`and `@mixin`but I don't see it. Only thing I've found is this suspicious line

https://github.com/GenieFramework/Stipple.jl/blob/a72d7612e7385719519b366b8781b6e9e1eac4ab/src/ReactiveTools.jl#L611

**Comment by hhaensel** [comment]
It has to do with when the macro is executed. I don't have the time to look into it directly. But there is an easy workaround; just split the handlers off with the `@handlers`macro:
```julia

@app Model begin
    @out var1 = 0
    @mixin mixstruct
end

@handlers begin
    @onbutton field begin
        println("button clicked")
    end
end
```

**Comment by hhaensel** [comment]
We have programmed the `@in`, `@out` and `@mixin` macros with many side effects. The reason for this was that we wanted to keep the syntax for the app macro identical to that of the script style for which the macros where initially designed for.
The only place where I didn't use `Core.eval()` is the one that now made the difficulties.
I think that this is successfully fixed in branch hh-mixin2. Please test before merging.
