### ISSUE TITLE
Allow to connect! app variable to an observable

### ISSUE THREAD

**Issue by yakir12** [GenieFramework/Stipple.jl#218]
[this is from [a discussion on Discord](https://discord.com/channels/774897545717219328/1144540195706896394/1144540195706896394)]

Is there a way to `Observable.connect!` a variable from an `@app` body to an `Observable`?

Something like this:
```julia
using Observables, MyModule

@app begin
    @in variable = 0
end

connect!(MyModule.some_observable, variable)
```

Right now I do this:
```julia
@onchange variable begin
    MyModule.some_observable[] = variable
end
```

**Comment by hhaensel** [comment]
The question is, what are you going to achieve. You have to be aware that every refresh of the page in the browser creates a new model and upon creation of that model the model's variable needs to be connected to your Observable. That's nicely done by your
```julia
@onchange variable begin
    MyModule.some_observable[] = variable
end
```

Could you precisely describe what scenario you have in mind?
Maybe we find a solution then.

Otherwise, if you are not considering multi-user applications, you could work with a global model

model = @init

and  connect the model's variable directly.
```julia
connect!(your_observable, model.variable)
```
But you have to write your own route function in that case.

**Comment by yakir12** [comment]
This highlights how I'm "abusing" the Genie framework to my specific needs...

Yes, I have (by definition) only one user at a time, and cannot have multiple instances of the model. My use-case is a UI for controlling hardware: A user controls parameters used to control an LED strip and a Raspberry Pi camera (in a behavioral experiment with dung beetles). The RPI is connected to the user's laptop with an Ethernet cable and the RPI serves the generated website to the client. I love the fact that the user doesn't need to install anything to control the whole thing, just open a browser and navigate to a specific IP address.

Refreshing the page doesn't seem to pose any errors as of yet, perhaps because of how I set it up (you can see what it looks like for now here: https://github.com/yakir12/dancingqueen/tree/main/app).

**Comment by hhaensel** [comment]
In this case I think it is absolutely ok to work with a global model.
My current working horse for such apps is:
```julia
using GenieFramework
@genietools

@app begin
   @in x = "Enter to return"
   @out y = 0
   
   @onchange isready push!
end

model = @init

UI = Ref{Any}()

UI[] = [
    row(cell(class = "st-module", [
        h3("Input")

        row(textfield(class = "col-6", "Text Label", :x))
        row(numberfield(class = "col-6", "Number Label", :y))
    ]))

    row(cell(class = "st-module", [
        h3("Output")

        row("X: {{ x }}")
        row("Y: {{ y }}")
    ]))

]

ui() = UI[]

route("/") do
    global model

    page(model, ui) |> html
end

up(open_browser = true)
```

**Comment by hhaensel** [comment]
When you need faster responsiveness, consider using named apps and make the following changes:
```julia
# in this example I name the handlers function "myhandlers"
# if you don't specify the name it will be called 'handlers'
@app MyApp begin
   @in x = "Enter to return"
   @out y = 0
   
   @onchange isready push!
end myhandlers

model = init(MyApp, debounce = 0) |> myhandlers
```

**Comment by hhaensel** [comment]
> you can see what it looks like for now here: https://github.com/yakir12/dancingqueen/tree/main/app
This has some similarity to my [CameraWidget.jl](https://github.com/GenieFramework/StippleDemos/blob/master/AdvancedExamples/CameraWidget.jl) Maybe you find some inspiration there how I managed the on/off problem.

**Comment by hhaensel** [comment]
Just to comment on your solution

```julia
@onchange variable begin
    MyModule.some_observable[] = variable
end
```
sounds perfectly fine for me. It won't use a different mechanism for triggering than `connect!()` does. Have a look at the following snippet:
```julia
julia> o1 = Observable(1);
julia> o2 = Observable(2);

julia> connect!(o1, o2)
ObserverFunction defined at C:\Users\helmu\.julia\packages\Observables\PHGQ8\src\Observables.jl:539 operating on Observable(2) 

julia> Observables.listeners(o1)
Pair{Int64, Any}[]

julia> Observables.listeners(o2)
1-element Vector{Pair{Int64, Any}}:
 0 => Observables.var"#11#12"{Observable{Int64}}(Observable(2))
```
So calling `connect!()` does nothing else than creating a listener that updates `o1` with the value of `o2` on any update or notification of `o2`. That's also what you do with your manual solution which you could write in a shorter form:
```julia
@onchange variable MyModule.some_observable[] = variable
```
But you could also do
```julia
model = init(MyApp, debounce = 0) |> myhandlers
connect!(MyModule.some_observable, model.variable)
```
I, personally, would opt for your proposal, because you have all callbacks in one place.

**Comment by hhaensel** [comment]
Just submitted a [PR](https://github.com/GenieFramework/Stipple.jl/pull/222) that would allow for the following usage
```julia
@page("/", ui, model = model)
```

**Comment by yakir12** [comment]
> > This has some similarity to my [CameraWidget.jl](https://github.com/GenieFramework/StippleDemos/blob/master/AdvancedExamples/CameraWidget.jl) Maybe you find some inspiration there how I managed the on/off problem.

Wow, I wish that worked with the new `GenieFrameworks` (right now  just get `ERROR: LoadError: UndefVarError: `@vars` not defined`). Very cool, thanks.

**Comment by essenciary** [comment]
> > This has some similarity to my [CameraWidget.jl](https://github.com/GenieFramework/StippleDemos/blob/master/AdvancedExamples/CameraWidget.jl) Maybe you find some inspiration there how I managed the on/off problem.
> 
> Wow, I wish that worked with the new `GenieFrameworks` (right now just get `ERROR: LoadError: UndefVarError: `@vars` not defined`). Very cool, thanks.

That was developed with an older version of Stipple. Replace `@vars` with `@app`

**Comment by essenciary** [comment]
Can this issue be closed?

**Comment by yakir12** [comment]
> Can this issue be closed?

Absolutely. However, it would be cool to entertain the Genie's use-case as a single-user GUI. I'll leave it at that for now, but maybe at some point in the future there can be some documentation directed at that solution.
