### ISSUE TITLE
Add support for ComplexF64 as reactive variables

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/Stipple.jl#235]
From https://discord.com/channels/774897545717219328/1167508826237435974/1167508826237435974

When declaring a reactive variable with type `ComplexF64`, an InexactError appears on page load. MWE:

```julia
using GenieFramework
@genietools

@app begin
    @out this_triggers_InexactError = ComplexF64(1.0 +1.0im)
    @onchange isready begin
        @show this_triggers_InexactError
    end
end

function ui()
    "{{this_triggers_InexactError}}"
end

@page("/", ui)
Server.isrunning() || Server.up()
```

Error trace

```julia
julia> ┌ Error: 2023-10-27 09:54:30 InexactError: Float64(1.0 + 1.0im)
│ Stacktrace:
│   [1] Real
│     @ ./complex.jl:44 [inlined]
│   [2] #construct#1
│     @ ~/.julia/packages/StructTypes/AK4aM/src/StructTypes.jl:327 [inlined]
│   [3] construct
│     @ ~/.julia/packages/StructTypes/AK4aM/src/StructTypes.jl:327 [inlined]
│   [4] write(::StructTypes.NumberType, buf::Vector{UInt8}, pos::Int64, len::Int64, x::ComplexF64; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│     @ JSON3 ~/.julia/packages/JSON3/L8Yfy/src/write.jl:266
│   [5] write(::StructTypes.NumberType, buf::Vector{UInt8}, pos::Int64, len::Int64, x::ComplexF64)
│     @ JSON3 ~/.julia/packages/JSON3/L8Yfy/src/write.jl:251
...
```

It seems that for complex numbers to work in the browser, we'd need to add some math library like [mathjs](https://mathjs.org/). Otherwise, we could define a custom renderer like

`Stipple.render(x::ComplexF64) = Dict(:re => x.im, :im => x.re)
`

**Comment by hhaensel** [comment]
Serialisation and deserialisation are already well-defined by https://mathjs.org/docs/core/serialization.html, so our render function would look like this:
```julia
Stipple.render(x::Complex) = Dict(:mathjs => "Complex", :re => x.re, :im => x.im)
```
But we would need to add the mathjs library and a respective reviver.

**Comment by hhaensel** [comment]
@essenciary two questions:

1. Where should we place StippleMathjs?

It could live within Stipple. The module is just 20 lines long plus the 700kB of math.js.
It's a very good example of how extra modules can be built.

2. How can we include initial values of revived types in the model.js file

Currently, if we use the reviver concept, the object to be revived are typically rendered as Dicts. So during their first initialisation they are a js object. Only if we push the variables the first time, e.g. by `@onchange isready @push" in the app definition, they receive their correct values. Any idea about that?

**Comment by hhaensel** [comment]
A solution for 2) is to define `jsrender(x, args...) = render(x, args...)` and to use that for field rendering in models.

Then one could specialise `jsrender(x::Union{Complex, R{<:Comnplex}) = myrender(Stipple.Observables.to_value(x))`, where `myrender` converts to a `JSONText`

**Comment by essenciary** [comment]
@hhaensel as discussed over messaging, the best approach would be to have a package similar to StippleLatex.

**Comment by hhaensel** [comment]
Find here the first draft of [StippleMathjs](https://github.com/GenieFramework/StippleMathjs) and the [StippleMathjsDemo](https://github.com/GenieFramework/StippleDemos/tree/master/AdvancedExamples/StippleMathjsDemo).

It only works with the hh-revivers branches currently. For this to work I added
- a new method to add custom revivers: `script(js_add_reviver("myreviver"))`
- a new method to add custom dependencies to ReactiveModels: `@deps StippleMathjs`

**Comment by hhaensel** [comment]
All changes are merged into master and new versions are released.
StippleMathjs has been registered and will be released after the mandatory waiting period of 3 days.
