### ISSUE TITLE
GenieAuthentication.get_authentication always returns nothing

### ISSUE THREAD

**Issue by svilupp** [GenieFramework/Stipple.jl#242]
This issue exists across several packages (GenieSession, GenieAuth, Stipple), but I chose to report it here, as I believe the bug has been introduced by a PR here.

**Behaviour:** 
If your Stipple application calls `get_authentication` you'll always get `nothing` even if the user is logged in.

**Root cause:**
I believe the problem has been introduced in [this commit](https://github.com/GenieFramework/Stipple.jl/commit/6aeeba96e5d4d2fdaea6dcc699304167b3e064cc#diff-39019d8ae899bcdd3758db28f205d5c546be80ab59858397e829ce82fa2e9f38) by hard-coding session key in the `Genie.Requests.payload()` to `:session` (line 462 in Stipple.jl).

This key tends to be set to const / hardcoded in other packages as `:SESSION` (eg, see https://github.com/GenieFramework/GenieSession.jl/blob/513dee7ca5c4bbd21d004b0c9e731d99db023d56/src/GenieSession.jl#L7).

Example:
If you run `@info keys(Genie.Requests.payload())` in your app, you'll see that these are available:

> [ Info: [:action_controller, :WS_CLIENT, :payload, :action, :REQUEST, :CHANNEL, :RESPONSE, :FILES, :POST, :GET, :controller, :session]

However, `GenieAuthentication.get_authentication()` tries to access the session object under the key `:SESSION`

**Impacted versions:**
- Stipple 0.27.18 (This wasn't a problem in Stipple 0.27.0)
- Julia 1.10 rc1

I'll open a PR for the fix // It's more of a reversion of a change, so perhaps there was a reason for the change?

___
If someone finds this and needs a quick fix to get a username across different versions of Stipple 0.27, I use:
```
# this overrides the method, so be careful!
function GenieAuthentication.get_authentication(params::Dict = Genie.Requests.payload())::Union{
        Nothing,
        Any,
    }
    session = if haskey(params, :SESSION)
        params[:SESSION]
    elseif haskey(params, :session)
        params[:session]
    else
        nothing
    end
    !isnothing(session) ? get_authentication(session) : nothing
end
```

If you want to be safe, just create a dedicated function with a different name:
```
using GenieSession
using GenieAuthentication

"Get username from the current `session` if available."
function get_username(params::Dict = Genie.Requests.payload())::Union{
        Nothing,
        Any,
    }
    session = if haskey(params, :SESSION)
        params[:SESSION]
    elseif haskey(params, :session)
        params[:session]
    else
        nothing
    end
    !isnothing(session) ? GenieSession.get(session, GenieAuthentication.USER_ID_KEY) :
    nothing
end
```

**Comment by essenciary** [comment]
@svilupp Thanks for the PR. Long story short, the change is due to a breaking refactoring in Genie v6 -- which has not yet been released, but some of these changes in other packages accidentally ended up in release. 🫣

**Comment by essenciary** [comment]
I've just tagged v0.27.25 of Stipple.jl for release with the merged PR. Please try it out. I'll close the issue - feel free to reopen or create a new one if more changes are needed.
