### ISSUE TITLE
Sessions are being synced across users

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/Stipple.jl#259]
If I open the same app in two different browser windows, their state is shared. Any reactive variable changing in one will also change in the other. 

Here's a MWE and a gif

```julia
module App
using GenieFramework
@genietools

@app begin
    @out x = 0
    @onchange isready begin
        while true
            x = x + 1
            sleep(1)
        end
    end
end

function ui()
    [bignumber("Count", :x)]
end

@page("/", ui)
Server.isrunning() || Server.up()
end

```
![CleanShot 2024-02-02 at 19 45 25](https://github.com/GenieFramework/Stipple.jl/assets/5058397/dfe3f729-c470-4e1f-acc5-a56469d65025)

You can also check with a deployed app:
https://apps.peregimenez.com/stock

Package versions:

  [a59fdf5c] GenieFramework v2.0.0
  [4acbeb90] Stipple v0.28.0

**Comment by hhaensel** [comment]
Did you make similar tests in the past?
We had one release, where the channels were shared and the channel was stored as session cookie.
From that time the browsers may have synchronised their channels.
So please for second testing delete all browser cookies for localhost.
I added tests to exclude channel-sharing, so in principle that shouldn't happen.

**Comment by essenciary** [comment]
Yes, they're not. 
<img width="1512" alt="image" src="https://github.com/GenieFramework/Stipple.jl/assets/11292378/d2bd9bdf-8019-48f5-9fdf-d8c77a7b5375">

**Comment by PGimenez** [comment]
I tried with different browsers and had the same issue, and I remember testing this before without issues. But I opened two incognito windows and the sessions were indeed not synced, so we can close this.

**Comment by sara2512** [comment]
How was this resolved? I currently experience the same issue across users at different computers. Channels are not(!) identical and stored in the session.

**Comment by essenciary** [comment]
@sara2512 Yes, it was a bug that affected a certain version. It has been patched. Can you make sure that you are running the latest version? 

If the issue persists, please provide:
1/ code that allows us to replicate the issue
2/ output of pkg> status
3/ output of julia> versioninfo()

Thanks!

**Comment by sara2512** [comment]
Thanks for the quick answer. Reading the original post again, I think the issue I'm seeing is a different one (some information is shared between sessions) and might as well be in my code. If I find anything that points to Stipple, I will let you know.

**Comment by sara2512** [comment]
To close this - the problem was indeed deeply hidden in my code. I accidently made use of a global model in one instance. No Stipple issue at all!
Sorry for that and thank you for taking the time.

**Comment by essenciary** [comment]
Yeee! Thanks for the update.
