### ISSUE TITLE
Sessions are linked together

### ISSUE THREAD

**Issue by narawat** [GenieFramework/Stipple.jl#265]
Hello,
I'm trying to build web app with multiple app modules similar to this Genie tutorial:
https://learn.genieframework.com/docs/guides/adding-reactive-pages#multiple-app-modules

However, sessions seem to be linked together if multiple user open the same route. To confirm, I tried the above Genie example without any modification.
https://github.com/narawat/Ai_playground/blob/master/Screenshot%20from%202024-03-09%2017-12-47.png

The result is the same. I test with Firefox and Edge in private windows.
https://github.com/narawat/Ai_playground/blob/master/Peek%202024-03-09%2015-28.gif

Package versions: 
Julia v1.10.2
GenieFramework v2.1.0

Is this normal behavior?

**Comment by narawat** [comment]
Thanks essenciary. Happy to report that your suggest works!. I also make the docs PR.

**Comment by hhaensel** [comment]
I think we shouldn't close this, but rather fix it. I'll have a look where the issue comes from.

**Comment by hhaensel** [comment]
Just added a potential fix for the issue.
@narawat could you try your original version with the hh-multipage-fix branch?

You can switch to that branch by entering
```julia
pkg> add Stipple#hh-multipage-fix
```
in the package manager.

**Comment by narawat** [comment]
The example works as it should now. Thanks.
Btw, Is it possible to use async MQTT client (MQTTClient.jl) inside a module? I'm would like to connect a reactive control dashboard to MQTT-based services to monitor/manage/control IoT devices. I think Genie have great potential in this area too.

**Comment by hhaensel** [comment]
Thanks a lot for checking!
I'll add tests for this issue and will merge soon.

Concerning MQTT I remember that we had an issue in the past. I propose that you build a MWE and open a new issue with that. Let's see whether we can help you.

**Comment by hhaensel** [comment]
Here's a Genie issue containing a MWE. Didn't read through it yet, though.
https://github.com/GenieFramework/Genie.jl/issues/702
