### ISSUE TITLE
element order depending on the viewport size

### ISSUE THREAD

**Issue by montyvesselinov** [GenieFramework/Stipple.jl#269]
Is there way to contol the order of elements depending of the viewport size.

Is there class like "order-xs-1" and "order-xs-2" which is change the order of elements for the case of xs

```
function ui()
    [
        Stipple.row(class = "q-col-gutter-md", [
            Stipple.htmldiv(class="order-xs-2", xs=5, sm=4, md=3, lg=2, xl=1,
                Stipple.cell(class = "st-module q-pa-sm full-height", "Hello, World long long long long long long long long long long long long long long long long long long long long long long long!")
            ), 

            Stipple.htmldiv(class="order-xs-1",  xs=7, sm=8, md=9, lg=10, xl=11,
                Stipple.cell(class = "st-module q-pa-sm full-height", "Hello, World long long long long long long long long long long long long long long long long long long long long long long long!")
            )
        ])

        Stipple.row(class = "q-col-gutter-md", [
            Stipple.htmldiv(xs=5, sm=4, md=3, lg=2, xl=1,
                Stipple.cell(class = "st-module q-pa-sm full-height", "Hello, World long long long long long long long long long long long long long long long long long long long long long long long!")
            ),

            Stipple.htmldiv(xs=6, sm=7, md=8, lg=9, xl=10,
                Stipple.cell(class = "st-module q-pa-sm full-height", "Hello, World long long long long long long long long long long long long long long long long long long long long long long long!")
            )
        ])
    ]
end
```

**Comment by PGimenez** [comment]
Unfortunately, Quasar does not support viewport-specific ordering, only generic ordering as shown [here](https://quasar.dev/layout/grid/introduction-to-flexbox#order). 

What might work is using classes from TailwindCSS, which support adding a prefix to filter by screen size. See their [docsf](https://tailwindcss.com/docs/responsive-design)

You can[ easily add Tailwind](https://learn.genieframework.com/docs/reference/reactive-ui/styling#using-tailwind-css) to your app with 
```julia
Stipple.Layout.add_script("https://cdn.tailwindcss.com")
```

**Comment by montyvesselinov** [comment]
Thank you, Pete! We use TailwndCSS and Bootstrap. Both allow for element ordering. Thank you for the tip.

I was not aware that you can switch to TailwndCSS in Genie. This is excellent! Our web designer will love it :-)
