### ISSUE TITLE
Registering version v0.9.0

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#27]
@essenciary Somehow, I can't release version v0.9.0 without it being the latest release. So currently I deleted the v0.9.0 release and just kept the tag. Perhaps you could help me here? (First time I'm tagging and defining releases ...)
Anyhow, v.0.9.1 is pulled correctly during update as well as the other packages StippleUI and StippleCharts.

**Comment by essenciary** [comment]
What is the highest tagged release now? Did v0.9.1 go through?

**Comment by hhaensel** [comment]
Yes that passed!

**Comment by hhaensel** [comment]
The ordering of the tags is strange. Are they ordered by submission date?

**Comment by hhaensel** [comment]
That was the point. Got it right now!

**Comment by essenciary** [comment]
How did that work? Did the registrator allow v0.9 after 0.9.1? If not, I think we can just skip v0.9, Pkg will resolve it successfully, I hope. And we can release a v0.10 soon, to sort things out.
