### ISSUE TITLE
Stipple.table colors

### ISSUE THREAD

**Issue by montyvesselinov** [GenieFramework/Stipple.jl#270]
I do not see how to control the colors in Stipple.table? I got some weird invisible colors:

![image](https://github.com/GenieFramework/Stipple.jl/assets/5632376/28f6513e-4c03-47ba-8bda-0f99252bd211)

or

![image](https://github.com/GenieFramework/Stipple.jl/assets/5632376/6cb83136-09ee-421a-ba95-dfebc2e30c4a)

**Comment by PGimenez** [comment]
By default, tables should have a white/light grey pattern. See an example in the [component gallery](https://learn.genieframework.com/docs/reference/reactive-ui/component-gallery). Did you add any style customizations that would make it look like this?

You can also change the styling of the odd rows of the table by giving it an id with `table(id="datatable", ...)` and then targetting it with CSS:

```css
#databable tbody tr:nth-child(2n) {
    background: rgba(108, 177, 242, 0.03);
}
```

**Comment by montyvesselinov** [comment]
Oops! Now, I see what caused the stripes.

Now the light mode works.

I still have issues with the dark mode:

```
Stipple.table(:datatable; pagination=:datatable_pagination, dense=true, striped=false, flat=true, dark=true, hover=true)
```

![image](https://github.com/GenieFramework/Stipple.jl/assets/5632376/92436d1b-df24-483c-883c-672705e81119)

I tried to change the color and background:

```
tr {
background: #808080 !important;
color: #FFFFFF;
}
```

but it did not work. The only way to change colors in the table is using CSS, correct? Thank you!

**Comment by hhaensel** [comment]
The following `ui()` defintion makes adding a css unnecessary:
```julia
ui() = [table(:table,
    template("", var"v-slot:body-cell" = "props", [
        quasar(:td, [
            textfield("", R"table.data[props.key-1][props.col.name]", :dense, :borderless,
                input__class = Dict("text-red" => js"table.data[props.key-1][props.col.name] != ref_table.data[props.key-1][props.col.name]"),
                input__style = Dict("font-weight" => 400, "font-size" => "0.9rem") # standard settings from stipplecore.css
            )
        ])
    ]))
]
```

**Comment by hhaensel** [comment]
Added some code to StippleUI#master, to make styling and editing a breeze.
Hopefully, the idea behind it makes it to the quasar docs:  in https://github.com/quasarframework/quasar/issues/17051

**Comment by hhaensel** [comment]
Does this help you?
https://github.com/GenieFramework/StippleUI.jl/commit/990456a907e2f814b0e3503af9497212b3ce3f98
![318206820-baa47859-639c-43e1-94a9-50e7384fb1b9](https://github.com/GenieFramework/Stipple.jl/assets/31985040/e8f889bb-5c3d-483a-994f-cc2853f9fae1)

**Comment by montyvesselinov** [comment]
this is great! Thank you!
