### ISSUE TITLE
Stipple.select label font size

### ISSUE THREAD

**Issue by montyvesselinov** [GenieFramework/Stipple.jl#271]
```Stipple.select(:dataset; options=:datanames, class="text-p", style="font-size: 11px;", color="white", bgcolor="bg-grey-8", popupcontentclass="bg-grey-9", label="Dataset:", labelcolor="orange")```

How can I change the font size on the label under Stipple.select?

**Comment by PGimenez** [comment]
The easiest way would be to edit the CSS style of the label. Create the default CSS file at `public/css/genieapp.css` and add this style in it:

```css
div.q-field__label {
    font-size: 30px;
}
```
The css file will be automatically loaded when you launch the Genie app.

Alternatively, you can swap the label with another component using the `label` slot like this

```julia
module App
using GenieFramework
@genietools

@app begin
    @out datanames=["iris","mtcars"]
    @out dataset="iris"
end

ui() = [
        select(:dataset, options=:datanames, class="text-p",
               style="font-size: 16px;", color="white", bgcolor="bg-grey-8",
               popupcontentclass="bg-grey-9", label="Dataset:", labelcolor="orange", 
               [ template(var"v-slot:label"="scope", 
                          [
                           badge("Dataset", style="font-size:20px;padding-bottom:5px")
                          ])
               ]
              )
       ]


@page("/",ui)
end
```

**Comment by montyvesselinov** [comment]
Thank you! Pete!

Definitely, the template works! This is very helpful

```
[template(var"v-slot:label"="scope", [badge("Dataset", style="font-size:20px;padding-bottom:5px")]
```

I guess `public/css/genieapp.css` works only if we use the app. Currently we are not developing a Genie app. If we do not build an app, do Genie/Stipple still read public/css/genieapp.css or other CSS file by default? Thank you!

**Comment by montyvesselinov** [comment]
Actually I have a problem when I am not using "using".

In our codes we use explicit references and we avoid "using". We use only import.

When imported, it does not seem to work.

````
Stipple.select(:prospectivity; label="Plot attribute:", class="text-p", style="font-size: 11px;", dark=true, labelcolor="orange", options=:prospectivities, color="white", popupcontentclass="bg-grey-9", [Stipple.template(Stipple.var"v-slot:label"="scope", [StippleUI.badge("Dataset", style="font-size:20px;padding-bottom:5px")])])
```

**Comment by hhaensel** [comment]
It's just three typos:
- You need a comma after `:prospectivity`, not a semicolon
- You need an empty first argument to `template()` (either `""` or `nothing`)
- `var"v-slot:label"` shouldn't be prefixed by `Stipple`, it's a keyword argument, not a variable

This works
```julia
Stipple.select(:prospectivity,
	label="Plot attribute:", class="text-p", style="font-size: 11px;", 
	dark=true, labelcolor="orange", options=:prospectivities, 
	color="white", popupcontentclass="bg-grey-9", [
		Stipple.template(nothing, var"v-slot:label"="scope", [
			StippleUI.badge("Dataset", style="font-size:20px;padding-bottom:5px")
		])
	]
)
```

**Comment by montyvesselinov** [comment]
Thank you! It worked. I would still suggest scaling the label font size based on the accessible style font size.
