### ISSUE TITLE
"Could not decode a text frame as UTF-8" when continuously updating a variable in async task

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/Stipple.jl#290]
I'm trying to animate a plot by continuously updating its data in a loop. I also have some controls to alter the data. When I click on a control, the plot animation freezes for a split second, and then continues normally. The freezing also happens randomly when the app has been running for 1min.

Here's a MWE to reproduce the issue:

```julia
using GenieFramework
@genietools

@app begin
  @out t = 0.0
  @in x = 1.0
  @onchange isready begin
    @async begin
      while true
        t = t+0.1
        sleep(0.1)
      end
    end
  end
end
ui() = """<q-slider :min="0" :max="100" :step="1" v-model="x"/> {{t}}"""

@page("/", ui)
```

I believe this is an issue with the websocket. It shows a  "Could not decode a text frame as UTF-8" error and a new websocket needs to be created, hence introducing a delay.

![CleanShot 2024-10-08 at 18 25 16](https://github.com/user-attachments/assets/2fa9f7ba-085d-4125-a3c7-efe63a7e2076)

**Comment by hhaensel** [comment]
I saw this error when independent Tasks where updating model fields.
It seems that some webchannel messages are queued and some are not  but simply sent without precaution. If these overlap, messages are corrupted. This happens particularly for large model fields.

**Comment by essenciary** [comment]
Yes, looking into it this week (today/tomorrow)

**Comment by essenciary** [comment]
Released a series of fixes to mitigate this. Performance has improved considerably.
