### ISSUE TITLE
using Stipple  ... not working

### ISSUE THREAD

**Issue by Mirage10** [GenieFramework/Stipple.jl#3]
Hello!

I have added the package Stipple to the environment and want to start in julia 1.6 REPL with the line:
julia>using Stipple

the system states:
using Stipple
ERROR: ArgumentError: Package Stipple [4acbeb90-81a0-11ea-1966-bdaff8155998] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at ./loading.jl:998
 [2] require(::Base.PkgId) at ./loading.jl:927
 [3] require(::Module, ::Symbol) at ./loading.jl:922
 [4] run_backend(::REPL.REPLBackend) at /home/user/.julia/packages/Revise/BqeJF/src/Revise.jl:1184
 [5] top-level scope at REPL[1]:0

after this I tried Pkg.instantiate() . This had no effect

so using Stipple is currently not working.

Any help appreciated!

**Comment by xgdgsc** [comment]
https://github.com/GenieFramework/Stipple.jl/issues/1#issuecomment-668917784  Probably the same issue.

**Comment by essenciary** [comment]
Yes, looks like a Pkg/registry issue.

**Comment by Mirage10** [comment]
hello all.

is there a workaround to circumvent this issue?

**Comment by essenciary** [comment]
Maybe delete `~/.julia` (keep the `dev/` folder if you developed any packages) and try again.

**Comment by PallHaraldsson** [comment]
I also got this but master works (this far, didn't try further):

```
julia> @time using Stipple
[ Info: Precompiling Stipple [4acbeb90-81a0-11ea-1966-bdaff8155998]
 46.923068 seconds (4.36 M allocations: 265.484 MiB, 0.17% gc time)
```

so maybe tag a version?

**Comment by Mirage10** [comment]
here the julia version:
julia> versioninfo()
Julia Version 1.6.0-DEV.818
Commit 0bff5bf0c5* (2020-09-02 13:42 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by essenciary** [comment]
@PallHaraldsson I was curious as to why it doesn't work, but sure, we can tag a "maintenance" release if that fixes whatever breaks.

**Comment by PallHaraldsson** [comment]
I just know I got/get:

```
(@v1.6) pkg> add Stipple

julia> @time using Stipple
ERROR: ArgumentError: Package Stipple [4acbeb90-81a0-11ea-1966-bdaff8155998] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(pkg::Base.PkgId, cache::Base.TOMLCache)
   @ Base ./loading.jl:889
 [2] require(uuidkey::Base.PkgId, cache::Base.TOMLCache)
   @ Base ./loading.jl:818
 [3] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:813
 [4] top-level scope
   @ timing.jl:174

but not with:

(@v1.6) pkg> add Stipple#master
[..]
  [4acbeb90] ~ Stipple v0.1.0 ⇒ v0.2.0 `https://github.com/GenieFramework/Stipple.jl.git#master`
Updating `~/.julia/environments/v1.6/Manifest.toml`
  [da1fd8a2] ↓ CodeTracking v1.0.0 ⇒ v0.5.12
  [e2ba6199] ↑ ExprTools v0.1.1 ⇒ v0.1.2
  [8fc22ac5] + FilePaths v0.8.1
  [48062228] + FilePathsBase v0.9.5
  [c43c736e] ↑ Genie v0.19.0 ⇒ v1.1.0
  [c27321d9] + Glob v1.3.0
  [1019f520] ↑ JLFzf v0.1.1 ⇒ v0.1.2
  [682c06a0] ↑ JSON v0.21.0 ⇒ v0.21.1
  [6f1432cf] + LoweredCodeUtils v0.4.9
  [c8ffd9c3] ↑ MbedTLS_jll v2.16.6+1 ⇒ v2.16.8+0
  [295af30f] ↑ Revise v1.0.3 ⇒ v2.7.5
  [4acbeb90] ~ Stipple v0.1.0 ⇒ v0.2.0 `https://github.com/GenieFramework/Stipple.jl.git#master`
```

When I think about it, I'm not sure a tag for v0.2.0 would have fixed this...

I see: 
```
(@v1.6) pkg> add Stipple@v0.2.0
```
does the trick too, but then I would have to know to ask for that latest (non-tagged) version.

**Comment by Mirage10** [comment]
this leads to
(@v1.6) pkg> add Stipple@v0.2.0
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
ERROR: invalid version: "0.0.0"
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] semver_interval(m::RegexMatch)
    @ Pkg.Types ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/versions.jl:344
  [3] semver_spec(s::String)
    @ Pkg.Types ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/versions.jl:325
  [4] load_version(version::VersionNumber, fixed::Bool, preserve::Pkg.Types.PreserveLevel)
    @ Pkg.Operations ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:58
  [5] load_direct_deps(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel)
    @ Pkg.Operations ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:70
  [6] targeted_resolve
    @ ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1110 [inlined]
  [7] tiered_resolve(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Operations ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1097
  [8] _resolve
    @ ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1121 [inlined]
  [9] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Vector{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Linux)
    @ Pkg.Operations ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1136
 [10] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Linux, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:189
 [11] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:140
 [12] #add#22
    @ ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:67 [inlined]
 [13] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:67
 [14] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
    @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:403
 [15] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:381
 [16] do_cmd
    @ ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:376 [inlined]
 [17] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:545
 [18] #invokelatest#2
    @ ./essentials.jl:707 [inlined]
 [19] invokelatest
    @ ./essentials.jl:706 [inlined]
 [20] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/julia/usr/share/julia/stdlib/v1.6/REPL/src/LineEdit.jl:2434
 [21] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:1130
 [22] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:392

(@v1.6) pkg> 


by the way. In julia 1.5 I can now do add stipple  + using Stipple. Works fine for me. Problems occur only on 1.6

**Comment by essenciary** [comment]
@Mirage10 Glad that it works on 1.5. No similar incidents have been reported and Stipple went through multiple releases (v0.6) now. Unfortunately atm I don't have the bandwidth to support Stipple on nightly Julia. If it's still an issue on v1.6 and you can investigate, I'm happy to assist. 

Closing this - please reopen or comment if you have any updates.

**Comment by PallHaraldsson** [comment]
FYI: Works on Julia 1.6 (but see interesting timings).

This works in my 31 days old master:
```
(@v1.6) pkg> add Stipple

julia> @time using Stipple
[ Info: Precompiling Stipple [4acbeb90-81a0-11ea-1966-bdaff8155998]
 28.149455 seconds (5.78 M allocations: 335.044 MiB, 1.06% gc time)

vs. in my 5 days old master takes longer (above loading Revise and OhMyREPL automatically may have speeded up):

$ ~/julia-1.6-113afd9309/bin/julia --startup-file=no

julia> @time using Stipple
[ Info: Precompiling Stipple [4acbeb90-81a0-11ea-1966-bdaff8155998]
 34.695801 seconds (8.16 M allocations: 478.067 MiB, 0.92% gc time, 14.62% compilation time)

one oddidy, before I realized the likly reason for the speed difference, I tried to exit and run again:

(@v1.6) pkg> rm Stipple
ERROR: The following package names could not be resolved:
 * Stipple (not found in project or manifest)

[very strange as no typo...]

[..]

(@v1.6) pkg> rm Stipple
Updating `~/.julia/environments/v1.6/Project.toml`
  [4acbeb90] - Stipple v0.6.0
Updating `~/.julia/environments/v1.6/Manifest.toml`
  [c7e460c6] - ArgParse v1.1.0
  [781609d7] - GMP_jll v6.2.0+2
  [c43c736e] - Genie v1.7.3
  [708ec375] - Gumbo v0.8.0
  [528830af] - Gumbo_jll v0.10.1+1
  [77172c1b] - HttpCommon v0.5.0
  [e6f89c97] - LoggingExtras v0.4.2
  [39ec1447] - Millboard v0.2.5
  [49dea1ee] - Nettle v0.5.0
  [4c82536e] - Nettle_jll v3.4.1+1
  [4d1e1d77] - Nullables v1.0.0
  [4acbeb90] - Stipple v0.6.0
  [b718987f] - TextWrap v1.0.1
  [ddb6d928] - YAML v0.4.2

(@v1.6) pkg> gc
┌ Warning: Reading manifest file at /home/pharaldsson_sym/.julia/packages/OpenCV/XvJPQ/Manifest.toml failed with error
│   exception =
│    Could not parse manifest: TOML Parser error:
│    /home/pharaldsson_sym/.julia/packages/OpenCV/XvJPQ/Manifest.toml:15:1 error: invalid bare key character: '<'
│      <<<<<<< HEAD
│      ^            
└ @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:493
     Active manifest files: 3 found
     Active artifact files: 145 found
     Active scratchspaces: 1 found
    Deleted no artifacts, repos, packages or scratchspaces

(@v1.6) pkg> add Stipple

julia> @time using Stipple
  0.000460 seconds (313 allocations: 29.578 KiB)
```

**Comment by PallHaraldsson** [comment]
Maybe I spoke too soon, posting in case you need to follow up:

On more recent f9ee161277 (4 days old master)
```
julia> @time using Stipple
[ Info: Precompiling Stipple [4acbeb90-81a0-11ea-1966-bdaff8155998]
ERROR: LoadError: InitError: MethodError: no method matching Base.TOMLCache()
Closest candidates are:
  Base.TOMLCache(::Base.TOML.Parser, ::Dict{String, Base.CachedTOMLDict}) at loading.jl:215
  Base.TOMLCache(::Any, ::Any) at loading.jl:215
```

Might be fixed on latest, I did file some other bug, and it was a duplicate (of something already solved if I recall).

**Comment by amckay1** [comment]
To chime in, I just got this same issue "MethodError: no method matching Base.TOMLCache()" on Julia v1.6 and Stipple v0.9.9 and master that seems to be preventing precompilation. Running on ubuntu for what it's worth.
