### ISSUE TITLE
Custom components are not loaded (st-dashboard and st-big-number)

### ISSUE THREAD

**Issue by essenciary** [GenieFramework/Stipple.jl#34]
@hhaensel This happened in v0.8 (worked in v0.7) and I suspect it's related to the JS changes, potentially in Elements.jl
I tried to debug it but I don't understand what that code does. Can you please take a look? (Try the GermanCredits demo).

The components get loaded upon the first data sync, hence my suspicion that something doesn't get properly initialized upon page rendering anymore. 

https://user-images.githubusercontent.com/11292378/110219137-c2613000-7ebd-11eb-9169-dcaafa30526f.mp4

```js
Vue warn]: Unknown custom element: <st-dashboard> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>) vue.js:634:17
[Vue warn]: Unknown custom element: <st-big-number> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)
```

**Comment by essenciary** [comment]
@hhaensel I found a workaround - not sure what caused it but forcing a Vue update upon load completed fixes the problem.

**Comment by hhaensel** [comment]
Good, you found the workaround, but I also have no clue, where this comes from. A bit annoying, as I also had used `window.onload` to setup custom payload parsing. I needed to start them with setTimeout...

**Comment by essenciary** [comment]
We're recruiting a senior frontend dev at Stipple so hopefully we'll soon have a dedicated programmer to cover all the JS parts 🤞 Btw, if you know any good candidate, please put us in touch.

**Comment by multidis** [comment]
@essenciary would you mind sharing your workaround to prevent Vue-warnings about custom components registration (e.g. the `dashboard1`-component [here](https://github.com/GenieFramework/StippleDemos/blob/master/GermanCredits/GermanCredits.jl))?

Would be great to get rid of those ugly warnings in the console (and anything else they potentially cause)... We are evaluating Stipple for single-user dashboard development and would like to have a clean start.

**Comment by essenciary** [comment]
@multidis @hhaensel The issue should be fixed in v0.18.2 - can you please check and confirm? 
I'll close this now, please reopen if necessary.

**Comment by multidis** [comment]
Confirming - no more custom component warning with Stipple `v0.18.2`. Thank you @essenciary !

**Comment by essenciary** [comment]
🥳

**Comment by multidis** [comment]
Sorry did not mean to put that stuff in - new to emojis and was trying to figure out what that one meant...
