### ISSUE TITLE
Connect a function to a btn

### ISSUE THREAD

**Issue by yakir12** [GenieFramework/Stipple.jl#37]
I'd like a Julia function to be called when the user presses a `btn`, so for each `btn` I have defined a model boolean parameter, and I use this custom `flipon` function:
```julia
flipon(f::Function, r::R{Bool}) = on(r) do tf
    if tf
        f()
        r[] = false
    end
end
```
to then connect a function, `f`, to that button.

For instance, to connect a `save` function to a "Save" `btn`, I have:
```julia
flipon(save, model.save)
```

Is there another obvious way I missed, or should we include this somehow?

**Comment by hhaensel** [comment]
That sounds like a good idea. I'd name the function `onbutton()`

```
onbutton(f::Function, button::R{Bool}; async=false, kwargs...) = on(button; kwargs...) do pressed
    pressed || return
    async ? @async(f()) : f()
    button[] = false
    return
end
onbutton(button::R{Bool}, f::Function; kwargs...) = onbutton(f, button; kwargs...)
```

Then we could either write
```
onbutton(model.save, save)
```
or
```
onbutton(model.save) do
    # save what has to be saved
end
```
(Similar to the `route()` syntax). We might even be tempted to do
```
import Obervables.on
on(observable::Observables.AbstractObservable, f::Function; weak=false) = onbutton(f, button; weak=weak)
```

**Comment by hhaensel** [comment]
I could also imagine an additional syntax to the `@click` macro:
```
macro click(expr)
  quote
    x = $(esc(expr))
    if x isa Symbol
      "@click='$x = true'"
    else
      "@click='$(replace($(esc(expr)),"'" => raw"\'"))'"
    end
  end
end
```
so that you can do
```
julia> @click(:test)
"@click='test = true'"
```
@essenciary shall I commit that?

**Comment by essenciary** [comment]
Yes, sounds great!

**Comment by hhaensel** [comment]
Just pushed the  changes.

**Comment by hhaensel** [comment]
I also enhanced `@click` a bit more by modifier and added some help text, maybe the first one in Stipple 🤣  Enjoy!

**Comment by hhaensel** [comment]
New release is in place 😃.
@yakir12 I really liked your idea for `onbutton()`

Maybe we should define
```
const Button = R{Bool}
```
?

**Comment by yakir12** [comment]
> @yakir12 I really liked your idea for onbutton()

Thanks! I like everything you guys do here..!

An alias for `R{Bool}` sounds useful but it makes me wonder about the other widgets, should they too get aliases? What about the fact that a toggle also is a `R{Bool}`. `R{String}` can often be an `input` but not always... This seems like it wouldn't be very consistent. Unless someone has many buttons in their dashboard, this seems like it would only save the user extra typing when they define their model's type. 

Another tempting shortcut (but again, with caveats) is to have the model be defined (even by a named tuple/dict) by the parameters' names and default values alone (via a function). The parameter types can be collected from their defaults and since everything is an Observable we don't need anything else than the names of the parameters and their default values. As a convenience function it seems fine, but it won't allow for Inner Constructor Methods to be defined (I find it very useful to connect some of the parameters in the model to each other, when it gets initiated).
