### ISSUE TITLE
' replacement changes input of textfields during reload

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#39]
@essenciary Your latest commit for charts corrupted the reload of textfields. Any `'` characters are now replaced by `"` characters.
Could you supply a MWE so that we can search for a different solution?

**Comment by essenciary** [comment]
Ugh - ok, this is getting very complicated and fragile. I'm working on adding unit and UI tests and we need to build a stable code-base with these. 

Until then, what path should we take? Don't think we can undo my fixes as they addressed plots rendering (in fact, any rendering of nested objects). Do you have an example for "reload of textfields"? I used the Hello example and worked fine.

**Comment by hhaensel** [comment]
Yes, that's the point, and even worse the page doesn't load anymore in most cases...

**Comment by essenciary** [comment]
Thanks, I'll look into it now.

**Comment by essenciary** [comment]
@hhaensel How do I reproduce it please? 

Seems to work fine
![image](https://user-images.githubusercontent.com/11292378/111691354-823f6d00-882e-11eb-8145-f2ed3f09ef7b.png)

**Comment by essenciary** [comment]
Ah ok on full page reload, the JS breaks because the `"` are not escaped: 
![image](https://user-images.githubusercontent.com/11292378/111691760-ebbf7b80-882e-11eb-8c0f-0542de41b78b.png)

**Comment by hhaensel** [comment]
I think we cannot afford to replace `'` by `"`, even if they would be escaped. I also need the `'` for the js functions...

**Comment by essenciary** [comment]
Yes, working to preserve the input as is.

**Comment by essenciary** [comment]
OK, I nailed it. In the end, the issue was with some specific JS support in `StippleCharts`/`ApexCharts` which needed proper JS `undefined` values. Added support for these in `Genie.Renderer.Js`, refactored `StippleCharts` and reverted `Stipple.Elements` to your initial code using pure `repr` output. 

Now I need to tag new versions of Genie (also merging your PR, thank you!), Stipple, and StippleCharts 😅

**Comment by hhaensel** [comment]
I created a new branch fir the ne Reactive type.
It works amazingly well

**Comment by essenciary** [comment]
@hhaensel should now work on the latest versions - can you please check and close the issue?

**Comment by hhaensel** [comment]
Great!
