### ISSUE TITLE
Dynamic content depending on view

### ISSUE THREAD

**Issue by JulesBlubb** [GenieFramework/Stipple.jl#40]
Hi, 
I would like to generate the UI depending on the view. That means dynamically create _html_ elements and also make them disappear depending on the click on an item for example. How do I do that with Stipple? (I have seen an example in the demos about dynamically created buttons, but this is still a work in progress.)
Thanks :)

**Comment by essenciary** [comment]
That's not an easy task even with hand coded JS. Hard to say without more details, but if you know in advance what you'll need, the easiest is to put them in the page and hide them, then control the visibility of the container. If it needs to be fully dynamic, you most likely need to have a JS function to create the elements and invoke that from Stipple. @hhaensel has more insight into this. 

@hhaensel related - should we think of an API to create and remove elements?

**Comment by hhaensel** [comment]
I'm not sure what your scenario is.
I have three proposals:
1) If you know the layout and only want to change contents, then you could probably use the [`v-if` semantic of Vue](https://vuejs.org/v2/guide/conditional.html).
We have macros in place to insert these clauses: `@iif`,`@elsiif`, `@els` (except that the `@iif` is currently corrupt, but we will fix it with the next release. (You can always code it manually by `"v-if=<condition>"`).

2) Use different ui-s if you have big changes and make a page reload

3) Use javascript. The latest version of the branch `hh-newReactive` supports execution of javascript in the backend. In the new [New API Demo Draft](https://github.com/GenieFramework/StippleDemos/blob/master/New%20API%20Demo%20Draft.jl) you can see how this can currently be implemented. As this is work in progress, the API might still be subject to change.

**Comment by hhaensel** [comment]
Short explanation on 1)
(When the fix is rolled out, better use the commented version.) 
```
using Stipple, StippleUI
import Stipple: opts, OptDict
Stipple.@kwdef mutable struct Example <: ReactiveModel
  name::R{String} = "Stipple!"
  visible1::R{Bool} = true
  visible2::R{Bool} = true
end

model = Stipple.init(Example())

function ui()
  [
    page(
      vm(model), class="container", title="Hello Stipple",
      [
        h1([
          "Hello, "
          span("", @text(:name))
        ])

        p([
          "Do you see me? "
          textfield("", :name, placeholder="type your name", label="Name", outlined="", filled="")
        ])
        p(
        #  toggle("visible 1", :visible1, "", @iif(:visible2))
          toggle("visible 1", :visible1, "", "v-if='visible2'")
        )
        p(
        #  toggle("visible 2", :visible2, "", @iif(:visible1))
          toggle("visible 2", :visible2, "", "v-if='visible1')
        )
      ]
    )
  ] |> html
end

route("/", ui)

up(open_browser=true)
```

**Comment by JulesBlubb** [comment]
Hi @hhaensel,
thank you very much for the example! This works perfect, except for _row_ or _cell._
I tried to hide multiple elements including charts. Therefore I need to use v-if also in row or cell. Is it possible to hide all elements in a cell? If not, how to hide an apexchart plot?
Thanks!

**Comment by hhaensel** [comment]
Sure, just wrap it in a `template([ ... ], v__if = :mybutton)`.
Make sure to supply a vector of strings to template and not just a string.

**Comment by hhaensel** [comment]
Just realised that the processing of `template` kwargs is different, so you need to do
```
template([ ... ], v__if = "mybutton")
```
@essenciary should we adapt this?

**Comment by hhaensel** [comment]
@JulesBlubb Can we close this?
