### ISSUE TITLE
Disabled toggle doesn't work

### ISSUE THREAD

**Issue by yakir12** [GenieFramework/Stipple.jl#42]
If I set `disabled` to `true` in a `toggle` then the toggle grays out and the "disable" icon comes up when hovering over the toggle, but I can still press it and all the side-effects still get executed.
MWE:
```julia
using Dates
using Stipple, StippleUI
using Genie.Renderer.Html

Base.@kwdef mutable struct Example <: ReactiveModel
    onoff::R{Bool} = false
    disable::R{Bool} = false
end

function togglefun(tf)
    if tf
        println("true", now())
    else
        println("false", now())
    end
end

function restart()
    global model
    model = Stipple.init(Example(), debounce=1)
    on(togglefun, model.onoff)
end

function ui()

    app = dashboard(vm(model),
        [
         heading("Example"),
         row(cell(class="st-module", [
                                      p(toggle("Toggle", fieldname = :onoff, disabled = :disable))
                                     ])),
        ], title = "Example")

    html(app)
end

route("/", ui)
Genie.config.server_host = "127.0.0.1"
restart()
up(open_browser = true)
```

**Comment by essenciary** [comment]
Thanks @yakir12 I'll check it out!

**Comment by hhaensel** [comment]
The reason is that Quasar expects a keyword `disable` and not `disabled`. Quite confusing that the mouse-pointer changes to disabled-mode nevertheless. But that's the underlying property that is changed by the disable-keyword.
@essenciary we should consider printing a warning when a user uses `disabled`.

**Comment by essenciary** [comment]
@hhaensel 

1. `disabled` is a valid HTML attribute and can be used.
2. we would have to check `disabled` in the context of `toggle` only - I'm wary of too many checks and conditions that will slow the library down and add extra code to maintain. 
3. plus what if the user really wants `disabled`? Warnings are expensive, we'd have to show it only once, keep track of state, etc.

I suggest once we have the documentation for the `toggle` we put a warning in the docs.

**Comment by hhaensel** [comment]
The disable keyword is available for most of Vue's input components, e.g. button, textfield, slider, ...

**Comment by essenciary** [comment]
Still, I'm not comfortable with polluting our codebase with this level of hand-holding. And the same goes for Quasar, as far as I can tell. I favor a documentation approach.

**Comment by hhaensel** [comment]
I'm also ok with the documentation approach. So let's close the issue?

**Comment by essenciary** [comment]
Awesome - closed! 🔥
