### ISSUE TITLE
Multi-user, multi-page Stipple site

### ISSUE THREAD

**Issue by NicholasWMRitchie** [GenieFramework/Stipple.jl#45]
I suspect that I just don't understand what I'm doing.  However, it almost works... 😃
```
using Genie
using Genie.Router
using Genie.Sessions

using Stipple
using StippleUI

Genie.config.session_storage = :File
Sessions.init()

# include("../config/secrets.jl")
Genie.secret_token!("707fe63722df866cbe7722654b39fcf44123cb6dc33794921c898fc5bab24e97") 

function get_model(sess::Session, sym::Symbol, build_model::Function)
    if !Genie.Sessions.isset(sess, sym)
        Genie.Sessions.set!(sess, sym, build_model())
        @info "Building $sym for $(sess.id)"
    else
        @info "Reusing $sym for $(sess.id)"
    end
    Genie.Sessions.get(sess, sym)
end  

Base.@kwdef mutable struct Page1 <: ReactiveModel
    name::R{String} = "You"
    namelen::R{Int} = 3
end
  
function build_page1()
    model = Stipple.init(Page1())
    on(model.name) do _
        model.namelen[] = length(model.name[])
        @info "Set namelen to $(model.namelen[])"
    end
    return model
end
  
function page1(sess::Session)
    page1_model = get_model(sess, :Page1, build_page1)
    @show page1_model.name[]
    [
        dashboard(
        vm(page1_model), class="container", title="Welcome", head_content=Genie.Assets.favicon_support(),
        [
            row(
            cell([
                h1([
                    "Greetings "
                    span("", @text(:name))
                    " with "
                    span("", @text(:namelen))
                    " characters in your name."
                ])
                p([
                "What is your name? "
                input("", placeholder="Type your name", @bind(:name))
                ])
            ])
            )
        ]
        )
    ] |> html
end

Base.@kwdef mutable struct Page2 <: ReactiveModel
    value::R{Int} = 13
    valueplus1::R{Int} = 14
end

function build_page2()
    model = Stipple.init(Page2())
    on(model.value) do _
        model.valueplus1[] = model.value[]+1
        @info "Set valueplus1 to $(model.valueplus1[])"
    end
    return model
end

function page2(sess::Session)
    page2_model = get_model(sess, :Page2, build_page2)
    @show page2_model.value[]
    [
        dashboard(
        vm(page2_model), class="container", title="You like integers?", head_content=Genie.Assets.favicon_support(),
        [
            h1([
                "My favorite integer is one less than "
                span("", @text(:valueplus1))
            ])
            row(
                cell(class="st-module",[
                "I like"
                slider(1:1:50,
                    @data(:value);
                    label=true)
                ])
            )
        ]
        )
    ] |> html
end


route("/") do
    sess = Sessions.session(Genie.Router.@params)
    page1(sess)
end

route("/Page2") do
    sess = Sessions.session(Genie.Router.@params)
    page2(sess)
end

up(8000, open_browser=true)
```
1. The first time I open "/" it works!!
2. When I open "/Page2" in another browser tab it works!!
3. But, "/" stops being interactive.  (This also happens if I open "/Page2" first and then "/", "/Page2" becomes unresponsive.)
4. If I open "/Page2" a different browser, the session id is different but they each update the other.  Different sessions track the same interactions.

1. If I restart the server, the Sessions get loaded from file.  The ReactiveModel don't get Init(...) 'd and everything fails.
2. Modifying the secret_token(...) before I restart the server and it works again.  (As it ought...)

1. The reactive data items in the ReactiveModel in the Session doesn't seem to be update when the model changes.

Thank you for your insight into what I'm doing wrong.

**Comment by essenciary** [comment]
It would be really helpful to break this long example with so many issues into single issue minimal examples. As is, it's too complex to debug. 

One thing I notice is, where have you defined `build_model`, used in `Genie.Sessions.set!(sess, sym, build_model())`

**Comment by hhaensel** [comment]
You have to set different channels for the different pages. That means modifying both the model's init routine and the user interface.
```
function build_page1()
    model = Stipple.init(Page1(), channel="__page1")
    on(model.name) do _
        model.namelen[] = length(model.name[])
        @info "Set namelen to $(model.namelen[])"
    end
    return model
end
```
and
```
function page1(sess::Session)
    page1_model = get_model(sess, :Page1, build_page1)
    @show page1_model.name[]
    [
        dashboard(
        vm(page1_model), class="container", title="Welcome", head_content=Genie.Assets.favicon_support(),
        [
            row(
            cell([
                h1([
                    "Greetings "
                    span("", @text(:name))
                    " with "
                    span("", @text(:namelen))
                    " characters in your name."
                ])
                p([
                "What is your name? "
                input("", placeholder="Type your name", @bind(:name))
                ])
            ])
            )
        ], channel = "__page1"
        )
    ] |> html
end
```
and in analogous way for page 2 (well, it is better style, but it would work, as page 1 doesn't conflict anymore)

**Comment by hhaensel** [comment]
@NicholasWMRitchie please close the issue if that works for you. We are trying to do some issue cleaning before the 1.0 release... 😄

**Comment by NicholasWMRitchie** [comment]
Thanks for your response.  I was unaware of channels.  I'm going to give this a try right now and close it ASAP.

**Comment by NicholasWMRitchie** [comment]
Adding "channel" in these two places does seem to separate the two pages and allow them to both operate simultaneously.  I'm still a little surprised that when I open the same URL in two different browsers, both browsers see the same page and update when the other is modified.

**Comment by hhaensel** [comment]
@essenciary is working on a good demo how to realise window-dependent sessions. (You will have to use cookies or other kinds of user identification to achieve what you want.)

**Comment by essenciary** [comment]
@NicholasWMRitchie agreed, that synced-state default behavior is surprising and not what most people want. We're working on an updated programming model where multi-user/independent states are the default.
