### ISSUE TITLE
New vue and quasar versions?

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#48]
@essenciary can we easily upgrade to a new quasar version by exchanging the js and css files?
Currently, we ship 1.11 while 1.15 is in place. The latter supports more symbols which I wanted to use for a private project.

Vue is only one version number behind, but we could replace it at the same occasion.

**Comment by essenciary** [comment]
Yes, have this on my list as well :) 
Upgrading to non-breaking version is fine. 
Planning to also upgrade to next major versions of Quasar and Vue (recently released) but that takes a bit of work - the idea is to do it after we have the tests for Stipple and have it for the v1 release.

**Comment by hhaensel** [comment]
How are the tests evolving? Can't wait to see the new API released.
BTW, I added an enhancement for slider by adding a lazy keyword

**Comment by essenciary** [comment]
The manual testing? Didn't get to that yet :-/ 

If it looks good to you, feel free to merge into master. Just maybe better not to tag a new version until I also test?

**Comment by hhaensel** [comment]
I don't think that it makes sense to merge before thorough testing. In case something goes wrong we don't have a branch to test against. Furthermore we should tag a new version for StippleUI together with the new Version of Stipple.

Could you give me a rough estimate, when you will be able to test?

**Comment by essenciary** [comment]
Ok - I will do it today.

**Comment by essenciary** [comment]
Updated JS files to latest non-breaking versions
