### ISSUE TITLE
"Pure julia"

### ISSUE THREAD

**Issue by KronosTheLate** [GenieFramework/Stipple.jl#55]
Hi

I just came here to check out the package, and this is one of the first thing I can see:
![image](https://user-images.githubusercontent.com/61620837/121011562-0999de00-c797-11eb-950b-b91d25c83586.png)

Writing "pure julia", while github reports 87% javascript, seems a little weird to me...

**Comment by essenciary** [comment]
The apps are developed in pure Julia. Stipple eliminates the need to write the front-end code, automatically generating the JavaScript, CSS and HTML code. In order to generate all this rich web frontend it uses JavaScript (among other things). What's the weird part?

**Comment by KronosTheLate** [comment]
I'll try and highlight what I found weird a little more:
![image](https://user-images.githubusercontent.com/61620837/121021576-d14bcd00-c7a1-11eb-9c78-29aab7b9e95d.png)
![image](https://user-images.githubusercontent.com/61620837/121021596-d6108100-c7a1-11eb-993b-6593311a0a4c.png)

Now I have NO idea how the numbers are estimated by github, or how stipple does things internally. My point is just that the above looks weird together, especially for a newcommer like me. Now I don't know what do to about it, and it is possible that the status quo is the best solution. I just wanted to point out something that the people regularily involved with the project might be blind to, but that newcomers might find weird.

**Comment by KronosTheLate** [comment]
> Thanks - can you please explain why is this important/relevant to you?

Now that is a little more tricky, which I get is your point. I agree that it is really nitpicky and really unimportant. My reaction when I read it was something along the lines of "oh, they write 'pure Julia' because it sounds good. And then GitHub, which does not lie, disproves it right after". Now, I trust the creators to really have meant something by "pure julia", and that it is probably true enough to justify writing it. But that is really a baseless assumption on my part. And without it, I get a bad impression.

 My thinking was simply that if there was a way to make this apparent inconsistency go away without any real cost, it would be good. If there is not, you are very free to close the issue.

**Comment by essenciary** [comment]
Thanks - yes, GitHub accepts a configuration which allows a repo to declare/overwrite the language stats.

**Comment by KronosTheLate** [comment]
> Thanks - yes, GitHub accepts a configuration which allows a repo to declare/overwrite the language stats.

That sounds perfect! Given, of course, that the library is in fact pure julia, whatever that means ^_^

**Comment by hhaensel** [comment]
If I may give my two cents to it...

"Pure Julia" in the Julia community is typically used to describe that no external binary packages are used. A famous packages that is not pure Julia is [FFMPEG.jl](https://github.com/JuliaIO/FFMPEG.jl), which is mainly a wrapper for ffmpeg. This is completely reasonable, as ffmpeg is a specialised and strongly optimised library. Nevertheless github stats tell it to be pure julia.

Very famous pure-Julia packages are [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl/blob/main/src/DataFrames.jl) or [CSV.jl](https://github.com/JuliaData/CSV.jl). You may try a pandas.read_csv versus CSV.jl and you will be surprised!

One thing quite a few Julia disciples are proud of is that Julia circumvents the 2-language problem, which most high-level languages like Python or R have. In their case, the high-performant scientific or mathematical code is typically written in C and the high-level language provides a wrapper. In Julia, also the high-performance code is written in - Julia! (Although writing high-performant code in Julia is an art 😉.) It is always possible to enhance existing packages without using another language, e.g. multi-threading features come with a snap of a finger - in pure Julia!

**Comment by essenciary** [comment]
It's really an issue of input and output. The key here is that the input is Julia (it's what the users code in) and the output is whatever it needs to be. In our case JS/CSS/HTML but in the future, if we start building Android or iOS apps it can be Java bytecode or iOS binaries. In order to generate the current JS/CSS/HTML certain files are included in the repo and GitHub indexes and tags them. I have addressed this, but the core idea is: the developer/user input is Julia and the output is whatever platform we're targeting (atm web). 

![image](https://user-images.githubusercontent.com/11292378/121389080-57a41280-c94c-11eb-92f0-77e2322b45ee.png)
