### ISSUE TITLE
Migrate from JSON.jl to JSON3.jl

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#59]
@essenciary After you have nicely moved all JSON code in Genie to JSON3, we could think about doing the same for Stipple.
Here are my 2 cents to it; define a JSONText equivalent in JSON3.
```
using JSON3, StructTypes

struct JSONText
    s::String
end

@inline StructTypes.StructType(::Type{JSONText}) = JSON3.RawType()
@inline StructTypes.construct(::Type{JSONText}, x::JSON3.RawValue) = JSONText(string(x))
@inline JSON3.rawbytes(x::JSONText) = x.s
```
All `JSON.lower` definitions would then need to be replaced by `JSON3.rawbytes()` plus the StructType definition, if I got it right.

**Comment by essenciary** [comment]
💯

**Comment by hhaensel** [comment]
I opened an issue in JSON3 https://github.com/quinnj/JSON3.jl/issues/168

I digged a bit deeper and think there are better options for lowering for most cases, namely [`StructTypes.lower()`](url)

**Comment by essenciary** [comment]
@hhaensel Anything we can do here?

**Comment by hhaensel** [comment]
We would need to replace `JSON.lower` by `StructTypes.lower` and register the type beforehand, e.g.
```julia
StructTypes.StructType(::Type{Undefined}) = StructTypes.CustomStruct()
StructTypes.lower(x::Undefined) = UNDEFINED_PLACEHOLDER
```
This is true for all packages like StippleCharts or StipplePlotly.
Furthermore we would need to replace `JSONParser.json` by `JSONParser.write` and define `const JSONParser = JSON3`
Are we going to do this?

Furthermore, I think we are not taking advantage of the structure mapping of JSON3, are we?

**Comment by hhaensel** [comment]
Oh, we could probably do something like
```julia
Core.eval(JSON3, :(import StructTypes.lower))
Core.eval(JSON3, :(const json = write; export json))
```
Then the adapations are pretty small. I'll try.

**Comment by hhaensel** [comment]
It seems that no packages use `JSON.lower()` yet, so we don't need the above lines. They would break incremental compilation anyhow 😉 
I'll prepare a PR ...

**Comment by essenciary** [comment]
Awesome! It was used for sure but we might've gotten rid of it. I'll run some tests with the PR too.
