### ISSUE TITLE
How to display image from local directory?

### ISSUE THREAD

**Issue by albertpod** [GenieFramework/Stipple.jl#66]
Hi, guys!

I've just started to play around with `Stipple.jl`. It looks great! Thanks a lot for your work! 

As a beginner, I am having trouble with some basic stuff, namely rendering local images (even after specifying the full path to the image), i.e.

```julia
using Stipple, StippleUI

#== reactive model ==#

Base.@kwdef mutable struct Model <: ReactiveModel
  imageurl::R{String} = "file://Users/user/Documents/stipple_demo/src/application/local.png"
end

const stipple_model = Stipple.init(Model())

#== ui ==#

function ui(stipple_model)
  dashboard(
    vm(stipple_model), class="container", [

      heading("SMTH")
      row([img(src=stipple_model.imageurl[], style="height: 100px; max-width: 100px")])
    ]
  )
end

#== server ==#

route("/") do
  ui(stipple_model) |> html
end

up()
```
I am getting this:
![Screenshot 2021-11-01 at 18 10 55](https://user-images.githubusercontent.com/8931177/139711683-1dc8abbe-2699-4618-9ef9-42c3e9a887b1.png)

Could you please tell me what am I doing wrong?

**Comment by hhaensel** [comment]
The image path is given with respect to the `[current working dir]/pub`.
So best create a directory pub in your cwd, create another directory img and place your file there. Then enter `/img/image.jpg` as your url

**Comment by hhaensel** [comment]
Why is this? A web server should never expose the true location of files. If that would work, without further work, any user could read your hard disk. So be happy, it doesn't 😉

**Comment by albertpod** [comment]
Thanks for the edit ;)
