### ISSUE TITLE
Fallback for synchronising typed Dicts

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#68]
After the latest releases synchronisation of typed Dicts is no longer working due to the elimination of the `try catch` block in `convertvalue()`.
This can be fixed by defining a general fallback for Dicts similar to the general fallback `Base.parse(::Type{T}, v::T) where T = v`:
```julia
function Base.parse(::Type{T}, value::Dict) where T <: AbstractDict
    convert(T, value)
end
```
@essenciary what do you think?

**Comment by essenciary** [comment]
Oops, sorry! You know that part best, your call!

**Comment by essenciary** [comment]
@hhaensel I've added it under the function you mention - will come in the next release ;)

**Comment by hhaensel** [comment]
I had pushed it tonight myself ...

**Comment by hhaensel** [comment]
I have another proposal to make before we release a new version.

**Comment by hhaensel** [comment]
I'll only have time later tonight. But I think, we can get rid of `convertvalue()` if we define the follwoing block:
```julia
function Base.parse(::Type{<:AbstractFloat}, value::T) where T <: Integer
  convert(valtype, value)
end

function Base.parse(::Type{T1}, value::T2) where {T1 <: AbstractArray, T2 <: AbstractArray}
  convert(T1, value)
end

function Base.parse(::Type{T}, value) where T <: AbstractArray
  convert(T, eltype(T)[value])
end

function Base.parse(::Type{T}, value::Dict) where T <: AbstractDict
  convert(T, value)
end

function Base.parse(::Type{T}, v::T) where {T}
  v::T
end
```

**Comment by essenciary** [comment]
@hhaensel I suggest we leave convertvalue() as I'm not comfortable with this approach. We're adding methods which will interfere with the functioning of other packages used within Stipple apps and lead to unexpected results (type piracy).

**Comment by essenciary** [comment]
So rather can we do the reverse, and add the Dict method back into convertvalue? @hhaensel  
It's a really bad practice to define common methods on types in Base.

**Comment by hhaensel** [comment]
I agree, but I thought you would stick to `Base.parse()` 😆 
So let's get rid of `Base.parse()` But that will bring some changes to other packages, right?

**Comment by essenciary** [comment]
@hhaensel I'm not sure I understand what you have in mind... `convertvalue` does not register methods, it only applies `convert` and `parse` methods. That's the best approach. 

I committed my changes but without the `AbstractDict` parse method. 

Can't we add a 

```julia
elseif valtype <: AbstractDict 
...
```

part in `convertvalue`

**Comment by essenciary** [comment]
Or... do you have a MWE to demonstrate the feature/failure please?

**Comment by hhaensel** [comment]
I've submitted a PR in order to explain what I had in mind ...

**Comment by hhaensel** [comment]
The current version works, so we can close this one. All the rest can be discussed in #71
Thanks @essenciary
