### ISSUE TITLE
Multiple User application 

### ISSUE THREAD

**Issue by cwiese** [GenieFramework/Stipple.jl#78]
Is this still relevant?  we need to handle and model per user ourselves and the routes need to contain a userid?

`https://github.com/GenieFramework/StippleDemos/blob/master/AdvanceExamples/MultiUserApp.jl` 

I guess I assumed the framework handled this and each user / thread has its own state/model.   

I tried this application and it must be outdated.  
            
######################### ERROR STACKTRACE #########################
MethodError: no method matching NamedTuple(::Dict{Symbol, Any}, ::Symbol, ::MyDashboard)
Closest candidates are:
  NamedTuple(::Dict{Symbol, T}, ::Symbol, !Matched::String) where T at /Users/charleswiese/.julia/packages/Stipple/5p8Kv/src/NamedTuples.jl:35
  NamedTuple(::Dict{Symbol, T}) where T at /Users/charleswiese/.julia/packages/Stipple/5p8Kv/src/NamedTuples.jl:15
  NamedTuple(::Any) at namedtuple.jl:107
Stacktrace:
  [1] dashboard(elemid::MyDashboard, content::Vector{String}; partial::Bool, title::String, head_content::String, class::String, style::String, channel::String, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ StippleUI.Dashboards ~/.julia/packages/StippleUI/BN82a/src/Dashboards.jl:30
  [2] ui(user::Int64)

**Comment by cwiese** [comment]
okay I updated - I have a different error for MultiUserApp.jl
```
  [c43c736e] Genie v4.5.0
  [4acbeb90] Stipple v0.18.3
  [30ddb3f0] StippleCharts v0.15.0
  [ec984513] StipplePlotly v0.8.0
  [a3c5d34a] StippleUI v0.12.0
```
```
┌ Error: MethodError: (::StippleUI.Dashboards.var"#dashboard##kw")(::NamedTuple{(:class, :title), Tuple{String, String}}, ::typeof(dashboard), ::MyDashboard, ::Vector{ParsedHTMLString}) is ambiguous. Candidates:
│   (::StippleUI.Dashboards.var"#dashboard##kw")(::Any, ::typeof(dashboard), elemid, content::Union{String, Vector{T} where T}) in StippleUI.Dashboards at /Users/charleswiese/.julia/packages/StippleUI/No3YA/src/Dashboards.jl:22
│   (::StippleUI.Dashboards.var"#dashboard##kw")(::Any, ::typeof(dashboard), model::M, args...) where M<:ReactiveModel in StippleUI.Dashboards at /Users/charleswiese/.julia/packages/StippleUI/No3YA/src/Dashboards.jl:36
│ Possible fix, define
│   (::StippleUI.Dashboards.var"#dashboard##kw")(::Any, ::typeof(dashboard), ::M, ::Union{String, Vector{T} where T}) where M<:ReactiveModel
│ Stacktrace:
│   [1] ui(user::Int64)

```

**Comment by cwiese** [comment]
okay I fixed dashboard() call - not error messages not console errors - but it does not work.    

All Web application are multi-user - seems every application would need this feature

**Comment by essenciary** [comment]
@cwiese Indeed, that's how it works as of recently: each client gets its own state and you need to opt in for sharing the state by assigning the same channel to the clients that should share state. I was actually working on these up until a few minutes ago. We still need to update all the demos to reflect the new API but here are some updated examples: 

https://github.com/GenieFramework/StippleDemos/blob/master/BasicExamples/HelloStipple.jl
https://github.com/GenieFramework/StippleDemos/blob/master/AdvanceExamples/MultiUserApp.jl

**Comment by cwiese** [comment]
thank you for the update!
