### ISSUE TITLE
Version 0.19.2: examples does not work

### ISSUE THREAD

**Issue by attdona** [GenieFramework/Stipple.jl#80]
with the latest 0.19.2 release the example does not work anymore:

The example output crossposted [here](https://discourse.julialang.org/t/stipple-reactivemodel-type-name-has-no-field-channel/73159)

Peeking at the code I got the following working, but I suspect that it will be not the intended new Stipple api because of explicit channel page argument (comments mark the changes):

```julia
using Genie, Genie.Renderer.Html, Stipple

#Base.@kwdef mutable struct Name <: ReactiveModel
@reactive mutable struct Name <: ReactiveModel
  name::R{String} = "World!"
end

#model = Stipple.init(Name())
model = Stipple.init(Name)

function ui()
  page(
    vm(model), class="container", [
      h1([
        "Hello "
        span("", @text(:name))
      ])

      p([
        "What is your name? "
        input("", placeholder="Type your name", @bind(:name))
      ])
    ], channel = model.channel__ # the channel assigned to model
  ) |> html
end

route("/", ui)

up()
```

May you add some insight?
I'm just learning Stipple and I'm quite impressed by its potential.

Many thanks!
Attilio

**Comment by hhaensel** [comment]
You're correct, are optimising the API and cannot keep all the examples up to date during that process

**Comment by AbhimanyuAryan** [comment]
@attdona most of the examples are updated to use new API. Please check and let me know if something doesn't work

**Comment by meeheal** [comment]
@AbhimanyuAryan 

New user to Stipple here! I have done some work in flexdashboard before though and looking to improve on all of that work by upgrading to Julia. It is a little slow going, but I have seen enough of Julia to know I need to do this for a) satisfaction, and b) continue to progress that work as the Julia packages in the field are growing but the R packages may or may not.

I am trying the first example from the Stipple GitHub page:

```
using Stipple

@reactive mutable struct Name <: ReactiveModel
  name::R{String} = "World!"
end

function ui(model)
  page( model, class="container", [
      h1([
        "Hello "
        span("", @text(:name))
      ])

      p([
        "What is your name? "
        input("", placeholder="Type your name", @bind(:name))
      ])
    ]
  )
end

route("/") do
  model = Name |> init
  html(ui(model), context = @__MODULE__)
end

up() # or `up(open_browser = true)` to automatically open a browser window/tab when launching the app

```

And I get the error: 

```

[ Info: Precompiling Stipple [4acbeb90-81a0-11ea-1966-bdaff8155998]
ERROR: LoadError: UndefVarError: @reactive not defined
in expression starting at Untitled-1:4


```

Was there another package I am supposed to have already added, that I don't have?

Thank you!

**Comment by hhaensel** [comment]
Hi @meeheal ,
to me that sounds as if you had an old version of Stipple installed. Please check:
```julia
]
pkg> st Stipple
```
The version should be `v0.22.0`.
Otherwise, please update
```julia
pkg> up Stipple
```

**Comment by meeheal** [comment]
I got that worked out with

` activate `

and now `up Stipple` is doing something it appears! Thanks for your help.

**Comment by meeheal** [comment]
I am providing an update. I had Julia 1.5.3 running when my problems described above occurred. I installed Julia 1.6.6, and while `up Stipple` still would not upgrade from Stipple 0.15.0 to 0.22.0, as Stipple was already added in the project.toml in the activated working directory in VSCode, when I then tried `activate` and `status` showed no packages, I added Stipple with `add Stipple` and finally, it is the correct version 0.22.0.

**Comment by hhaensel** [comment]
I think you are confusing
```julia
>pkg activate
```
and
```julia
>pkg activate .
```
The latter one activates the `Project.toml` of the directory where you are in.

There was another bug on our side; we had not included the latest Stipple versions in the Project.toml. I just changed that.
So for the future you can do 
```julia
pkg> activate .
pkg> up
```
to bring your Stipple packages up to date.
