### ISSUE TITLE
Support for PlotlyBase in StipplePlotly and StipplePlotlyExport

### ISSUE THREAD

**Issue by cwiese** [GenieFramework/Stipple.jl#86]
Updated to newest version of Geneir/Stipple/StippleUI 
```
┌ Warning: This method has been deprecated and will be removed soon. Please use `init(m::Type{M}, kwargs...)` instead.
└ @ Stipple ~/.julia/packages/Stipple/wjhHe/src/Stipple.jl:773
ERROR: type Model has no field channel__
```

Is this correct ?

```
Stipple.@kwdef mutable struct MainDash <: ReactiveModel
  channel__::AbstractString = Stipple.channelfactory()
  tab::R{String} = "home"
  models::R{Vector{String}} = String[]
```

and 

```
  dash_model = Stipple.init(MainDash)
```

I tried this and my Stipple application is Blank with no errors - I stipple see HTML in "inspect" mode .. but something is not "starting "with Vue

**Comment by essenciary** [comment]
Yes, that should work but I suggest to use the new API: 

```julia
@reactive mutable struct MainDash <: ReactiveModel
  tab::R{String} = "home"
  models::R{Vector{String}} = String[]
```

**Comment by cwiese** [comment]
I have a systemic issue with new version - nothing renders (I see the scripts) 

```
Julia Version 1.7.1 (2021-12-22)
pkg>  add Stipple StippleUI
Status `~/Documents/GitHub/py/Project.toml`
  [4acbeb90] Stipple v0.20.2
  [a3c5d34a] StippleUI v0.14.3

using Stipple, StippleUI

@reactive mutable struct PlotModel <: ReactiveModel
    name::R{String} =  "bar"
end 
dash_model = Stipple.init(PlotModel)

function ui()
    page(vm(dash_model), class="container", title="Interactive Analysis", 
        card( [card_section( span("", @text(:name)))
    ]))
end

route("/", ui)
up(open_browser=true)
```

**Comment by cwiese** [comment]
I can see "Name:"   but not "bar
```
using Stipple, StippleUI

@reactive mutable struct PlotModel <: ReactiveModel
    name::R{String} =  "bar"
end 
dash_model = Stipple.init(PlotModel)

function ui()
    page(vm(dash_model), class="container", title="Interactive Analysis", 
        card( [card_section( span("Hello:", @text(:name)))
    ]))
end

function ui()
    page(vm(dash_model), class="container", title="Interactive Analysis", [
        span("Hello:", @text(:name))
    ])
end

route("/", ui)
up(open_browser=true)
```

**Comment by hhaensel** [comment]
The syntax of `@text` is slightly different. You should not enter any explicit text in `span` in order to use the `@text` macro (see e.g. [v-text](https://vuejs.org/v2/api/#v-text)).
So your command should rather look like this:
```julia
["Hello: ",  span([], @text(:name))  ]
```
There is another syntax, which we currently don't support with macros, which is called interpolation, that uses double or triple [mustaches](https://vuejs.org/v2/guide/syntax.html?#Text).

So you could also do a simple
```julia
"Hello: {{ name }}"
```

**Comment by essenciary** [comment]
Drop the `vm(...)` call, it's no longer needed, just pass the model.

**Comment by cwiese** [comment]
still no "bar" from model 

```using Stipple, StippleUI

@reactive mutable struct PlotModel <: ReactiveModel
    name::R{String} =  "bar"
end 
dash_model = Stipple.init(PlotModel)

function ui()
    page(dash_model, class="container", title="Interactive Analysis", [
        ["Hello: ",  span([], @text(:name))  ]
    ])
end

route("/", ui)
up(open_browser=true)
```

**Comment by essenciary** [comment]
Ex of the new API: https://github.com/GenieFramework/StippleDemos/blob/master/BasicExamples/HelloStipple.jl

Sorry about the difficulty, we're almost at v1 and then no more breaking updates.

**Comment by essenciary** [comment]
Still not working? Please make a zip of the app and share.

**Comment by cwiese** [comment]
Okay... I got a test working ... trying bigger app

**Comment by cwiese** [comment]
Everything is working expt my new approach to PlotlyBase so can use features like "shapes" or subplots with 2 yaxis (many more).

1.  I have attached two files `test_plot.jl` - works fine with new stipple changes.
2. `test_plotbase.jl` - which is based on Plotlybase.jl - does not work 

In order to use Plotlybase I had to change Charts.jl 
```
using PlotlyBase: AbstractTrace, AbstractLayout
export AbstractTrace, AbstractLayout
```
#2 is a blank plot.

[Archive.zip](https://github.com/GenieFramework/Stipple.jl/files/7850567/Archive.zip)

**Comment by hhaensel** [comment]
@essenciary This issue comes from our migration from JSON to JSON3 😢 

JSON3 seems to nest an additional lay named "fields" when converting structs:
```julia
julia> JSON.json(model.data[])
"[{\"xaxis\":\"x\",\"yaxis\":\"y\",\"legendgrouptitle\":{\"text\":\"1 Group Title\"},\"col\":1,\"x\":[-3.141592653589793,-3.1164599123610746,-3.0913271711323564,-3.066194429903638,-3.0410616886749198,-3.015928947446201,-2.990796206217483,-2.9656634649887645,-2.9405307237600464,-2.915397982531328,-2.8902652413026098,-2.865132500073891,-2.839999758845173,-2.8148" ⋯ 19994 bytes ⋯ "\":1,\"x\":[-3.0,-2.0,-1.0,0.0,1.0,2.0,3.0],\"showlegend\":true,\"mode\":\"markers\",\"row\":2,\"name\":\"sinh\",\"plot\":\"scatter\",\"legendgroup\":\"group2\",\"marker\":{\"color\":\"#cc12dd\",\"symbol\":\"circle-open\",\"size\":14},\"y\":[-28.76908414177681,-22.32430094042556,-22.32729460652706,-20.267379064139064,-17.56354188848954,-17.061248220822698,-10.826090997393683]}]"

julia> JSON3.write(model.data[])
"[{\"fields\":{\"xaxis\":\"x\",\"yaxis\":\"y\",\"legendgrouptitle\":{\"fields\":{\"text\":\"1 Group Title\"}},\"col\":1,\"x\":[-3.141592653589793,-3.1164599123610746,-3.0913271711323564,-3.066194429903638,-3.0410616886749198,-3.015928947446201,-2.990796206217483,-2.9656634649887645,-2.9405307237600464,-2.915397982531328,-2.8902652413026098,-2.865132500073891,-2.83" ⋯ 20126 bytes ⋯ "0,-2.0,-1.0,0.0,1.0,2.0,3.0],\"showlegend\":true,\"mode\":\"markers\",\"row\":2,\"name\":\"sinh\",\"plot\":\"scatter\",\"legendgroup\":\"group2\",\"marker\":{\"fields\":{\"color\":\"#cc12dd\",\"symbol\":\"circle-open\",\"size\":14}},\"y\":[-28.76908414177681,-22.32430094042556,-22.32729460652706,-20.267379064139064,-17.56354188848954,-17.061248220822698,-10.826090997393683]}}]"
```

**Comment by hhaensel** [comment]
Just realised that the nesting with fields is from our side ...

Do we need it?

**Comment by essenciary** [comment]
?

If our frontend code works with that structure won't removing it break our code?

**Comment by hhaensel** [comment]
If we change our front-end code to generate dicts/structs without nested `fields`, we should probably be fine. But I would need to look into it a bit deeper

**Comment by hhaensel** [comment]
Correction:

The nesting with fileds comes from `PlotlyBase`. They use a JSON3 implementation that wraps JSON as they have defined lowering for their types.

The following lines solve the issue. We might propose a PR to JSON3 ...

```julia
using Stipple.StructTypes, Stipple.JSON3
StructTypes.StructType(::Type{<:AbstractTrace}) = JSON3.RawType()
JSON3.rawbytes(trace::AbstractTrace) = codeunits(JSON.json(trace))
```

**Comment by cwiese** [comment]
Awesome - thank you @hhaensel .     It worked.

**Comment by hhaensel** [comment]
😃 So can we close this or do we leave it open until PlotlyBase is patched?

**Comment by cwiese** [comment]
lets close it?

**Comment by hhaensel** [comment]
I propose that if `PlotlyBase` won't merge the PR, we will make a PR for `StipplePlotly`

**Comment by cwiese** [comment]
Very cool - and thank you for the help.

**Comment by essenciary** [comment]
I would also like to have support for `PlotlyBase` but I'm against having both JSON and JSON3 as dependencies.

**Comment by essenciary** [comment]
Potentially this also breaks StipplePlotlyExport which uses PlotlyBase. Renamed and reopened for further investigations.

**Comment by hhaensel** [comment]
PlotlyBase has JSON as dependency and includes wrappers for JSON3 via `@requires`

**Comment by hhaensel** [comment]
So we don't need to include JSON explicitly

**Comment by hhaensel** [comment]
PlotlyBase accepted my PR after some reviewing 😄 
They have a Union type `HasFields` for all types that are affected. So we finally ended up with a two-liner...
As soon as the next PlotlyBase version is tagged, we close this issue.
