### ISSUE TITLE
'$' sign not working `js_methods()`

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Stipple.jl#9]
Usage of '$' sign in `js_methods()` fails due to double backslashes from json renderer.
PR #8 addresses that issue.
Example code: `this.unwatch = this.\$watch("downloadtext", this.pushDownload);`

```
julia> Genie.Renderer.Json.JSONParser.json(raw"""this.unwatch = this.\$watch("downloadtext", this.pushDownload);""") |> println
"this.unwatch = this.\\$watch(\"downloadtext\", this.pushDownload);"
```
generates the double amount of backslashes needed.
`replace(..., "\\\\" => "\\")` solves the problem.

**Comment by essenciary** [comment]
@hhaensel Thank you, merged! 🎉🙌
