### ISSUE TITLE
Support for UTF with JSON3

### ISSUE THREAD

**Issue by essenciary** [GenieFramework/Stipple.jl#91]
zy_os — Yesterday at 5:39 PM
@essenciary to resolve this bug, I fould that it need to change Stipple.jl :39  @inline JSON3.rawbytes(x::JSONText) = x.s    ->   @inline JSON3.rawbytes(x::JSONText) = codeunits(x.s)

**Comment by hhaensel** [comment]
Very true!

**Comment by hhaensel** [comment]
@essenciary 
Are you doing it?

**Comment by essenciary** [comment]
Yes! Just want to test it before tagging a new release, to make sure it doesn't break anything.

**Comment by hhaensel** [comment]
Sounds good. Your fix looks should be ok. It's the same way how we fixed JSON3 for PlotlyBase ...

**Comment by essenciary** [comment]
This has been released yesterday in v0.20.4
