### ISSUE TITLE
Extend @R_str to allow escaped strings

### ISSUE THREAD

**Issue by mdotend** [GenieFramework/Stipple.jl#96]
I just stumbled upon an issue while using the macro **@R_str** in combination with variables. As macros execute the input in a different namespace, it is not possible to dynamically access e.g. array fields in a loop.

## Problematic behavior:
`@R_str "myArray[item.id]"` led to this error: _item not defined_

## Workaround / proposed fix:
I added another macro with an escaped string, which solved the problem for me:

```
macro R_str_esc(s)
  :(Symbol($(esc(s))))
end
```

**Comment by hhaensel** [comment]
Escaping for R_str is not a good idea. The reason is that Vue supports javascript expressions to be evaluated for its fields. Imagine you would have an array of tooltips `tips = ["Hello", "World"]` and you wanted to link the first array element to your tooltip. In html code this would read
```html
<q-tooltip v-model="tip[0]"></q-tooltip>"
```
With StippleUI this translates to
```julia
tooltip(fieldname = R"tips[0]")
```
This would not be possible to write with escaped syntax. Also note the zero-based indexing in javascript.

For your use case I'd rather go for converting it to `Symbol` explicitly:
```julia
tooltip(fieldname = Symbol(myArray[item.id])
```

**Comment by mdotend** [comment]
Thanks for the explanation!
Unfortunately, when I use the Symbol approach, there is no v-model created (at least for checkboxes). 
I suppose the reason is because it is accessing the value in the element and not the element itself.

**Comment by hhaensel** [comment]
Please supply your code here

**Comment by hhaensel** [comment]
I tested the following
```julia
julia> myarray = ["hello", "world"]
2-element Vector{String}:
 "hello"
 "world"

julia> checkbox.("hi", Symbol.(myarray))
2-element Vector{ParsedHTMLString}:
 "<q-checkbox label=\"hi\" v-model=\"hello\"></q-checkbox>"
 "<q-checkbox label=\"hi\" v-model=\"world\"></q-checkbox>"
```

So I don't see what's not working with `Symbol`, maybe some misunderstanding?

**Comment by mdotend** [comment]
I use an BitVector to store and process the input and this does not create the v-model. Maybe that is the issue:
```
julia> test = falses(2)
2-element BitVector:
 0
 0

julia> checkbox.("hi", Symbol.(test))
2-element Vector{ParsedHTMLString}:
 "<q-checkbox label=\"hi\"></q-checkbox>"
 "<q-checkbox label=\"hi\"></q-checkbox>"
```
In my App I also use it in a model with the Reactive wrapper, but this should not change the behaviour, right?

**Comment by hhaensel** [comment]
I think this is not, what you are aiming at. The checkbox function is part of the ui, which connects parts of the model with checkboxes on the front-end. So your html code should look like `checkbox("hi", R"myarray[0]")` for the first checkbox, `checkbox("hi there", R"myarray[1]")` for the second checkbox, etc.
Here's a working demo for what I think you are trying to achieve:

```julia
using Stipple
using StippleUI

@reactive! mutable struct Model <: ReactiveModel
    valone::R{Bool} = false
    valtwo::R{Bool} = false
    valthree::R{Bool} = false
    checks::R{Vector{Bool}} = falses(3)
end

function ui(my_model)
    page(
        my_model,
        class = "container",
        [
            checkbox(label = "Apples", fieldname = :valone, dense = true),
            checkbox(label = "Bananas", fieldname = :valtwo, dense = true),
            checkbox(label = "Mangos", fieldname = :valthree, dense = true),
        ],
        [checkbox("Checkbox $i", Symbol("checks[$(i-1)]")) for i in 1:length(my_model.checks[])]
    )
end

my_model = Stipple.init(Model)

route("/") do
    html(ui(my_model), context = @__MODULE__)
end

up(async = true)

```

**Comment by hhaensel** [comment]
The first three checkboxes are classical 1:1 mappings directly taken from the checkbox example in StippleDemos. The next three checkboxes are mapped to a bit-vector `checks` which is part of the model. You can update the checkboxes from Julia, e.g. by setting
```julia
my_model.checks[3] = true
```

**Comment by hhaensel** [comment]
If you like zero-based indexing also on the Julia backend then you can also use the package OffsetArrays and do 
```julia
@reactive! mutable struct Model <: ReactiveModel
    checks::R{OffsetVector{Bool, BitVector}} = OffsetArray(falses(3), -1)    
end

function ui(my_model)
    page(
        my_model,
        class = "container",
        [checkbox("Offset Checkbox $i", Symbol("checks[$i]")) for i in eachindex(my_model.checks[])]
    )
end
```

**Comment by hhaensel** [comment]
I added a demo in StippleDemos

**Comment by mdotend** [comment]
Thank you, that works as intended without the macro!
